export {
  listEntryRulesInEffect,
  matchLine,
  selectRule,
  type AccountGroupResolver,
  type RulesInEffectRequest,
  type SelectRuleOptions,
} from "./match.ts";
export {
  EntryAllocationError,
  type EntryAllocationErrorCode,
  explodeDocumentLine,
  loadEntryRuleByKey,
  planEntryDistributions,
  renderAllocationTemplate,
  type EntryDocumentContext,
  type EntryLineInput,
  type EntryPlan,
  type ExplodeOptions,
  type ExplodeResult,
  type KeyedEntryRuleLookup,
  type PlannedEntryLine,
  type PlannedEntryLineage,
  type PlanOptions,
  type StoredEntryGroup,
} from "./entry.ts";
export {
  AllocationApportionError,
  apportion,
  fixedPercentWeights,
  steppedWeights,
  type SteppedTier,
} from "./apportion.ts";
export {
  definitionHash,
  validateRuleVersion,
  type AllocationValidationProblem,
  type KnownDriver,
  type PublishedSiblingWindow,
  type RuleVersionValidationContext,
} from "./validate.ts";
// A1 rule service. listRulesInEffect is the canonical window/book-aware
// listing; match.ts listEntryRulesInEffect narrows it to current versions.
export {
  AllocationRuleError,
  createDraftVersion,
  createRule,
  deleteRule,
  getRuleDetail,
  getRuleVersion,
  listRuleHeads,
  listRulesInEffect,
  loadRuleInEffectByKey,
  publishVersion,
  replaceTargets,
  retireVersion,
  updateDraftVersion,
  updateRule,
  type AllocationAudit,
  type AllocationOrgScope,
  type AllocationTargetInput,
  type CreateRuleInput,
  type CurrentVersionSummary,
  type DraftVersionInput,
  type ListRulesInEffectInput,
  type ReplaceTargetsInput,
  type RuleDetail,
  type RuleHeadSummary,
  type RuleMutationResult,
  type RuleVersionTimelineEntry,
  type RuleVersionWithTargets,
  type TargetsMutationResult,
  type UpdateDraftInput,
  type UpdateRuleInput,
  type VersionMutationResult,
  type VersionTransitionInput,
} from "./rules.ts";
export type {
  AccountScope,
  AllocationApplyPolicy,
  AllocationDimension,
  AllocationDriver,
  AllocationDriverSourceKind,
  AllocationMode,
  AllocationRuleTarget,
  AllocationRuleVersion,
  AllocationRuleHead,
  ApportionedTarget,
  ApportionResult,
  ContributedLine,
  Coordinate,
  DimensionFilters,
  DriverAsOf,
  DriverResolveRequest,
  DriverResolver,
  DriverVector,
  DynamicTarget,
  LineageDraft,
  LineCoordinate,
  MatchResult,
  ReportDriverTemporal,
  ReportTemporalMode,
  RuleInEffect,
  UntaggableDimension,
  WeightedTarget,
} from "./types.ts";
export {
  DRIVER_SOURCE_KINDS,
  DriverAdminError,
  NATIVE_MEASURES,
  REPORT_TEMPORAL_MODES,
  createDriver,
  createDriverValue,
  deleteDriver,
  deleteDriverValue,
  driverValueWindowsOverlap,
  getDimensionValueLabels,
  getDriver,
  listDriverValues,
  listDrivers,
  parseAllocationDimension,
  updateDriver,
  updateDriverValue,
  validateDriverConfig,
  validateDriverKey,
  validateDriverValueDecimal,
  vectorShares,
  type CreateDriverInput,
  type DriverValueInput,
  type DriverValueRow,
  type UpdateDriverInput,
} from "./driver-admin.ts";
export {
  DriverNotAvailableError,
  createDriverResolver,
  driverResolver,
  previewDriverVector,
  type DriverPreview,
  type DriverPreviewRequest,
  type DriverResolveOptions,
  type DriverResolverDeps,
  type ReportDriverEvidence,
  type ReportDriverRow,
  type ReportDriverRunInput,
  type ReportDriverRunner,
  type ResolvedWindow,
} from "./drivers.ts";
export {
  RunQueryError,
  getRun,
  listRuns,
  queryLineage,
  runSubsidiaryVisible,
  validateLineageAnchor,
  type LineageAnchor,
  type LineageRow,
  type ListRunsFilter,
  type RunDetail,
  type RunSummary,
} from "./run-queries.ts";
export {
  allocationFingerprint,
  postAllocationRun,
  previewAllocationRun,
  rerunAllocationRun,
  reverseAllocationRun,
  staticDriverResolver,
  type AllocationRunRecord,
  type PeriodRunDeps,
  type PostAllocationRunOptions,
  type PreviewAllocationRunOptions,
  type RerunAllocationRunOptions,
  type RerunAllocationRunResult,
  type ReverseAllocationRunOptions,
} from "./period-run.ts";
export {
  getRun as getAllocationRun,
  listRuns as listAllocationRuns,
} from "./run-queries.ts";
export {
  ALLOCATION_RUN_OUTBOX_KIND,
  allocationRunOccurrenceKey,
  ensureAllocationRunOutboxRows,
  parseRunAllocationConfig,
  previewInputFor,
  processAllocationRunOutboxRow,
  runAllocationCloseAction,
  type RunAllocationConfig,
} from "./scheduling.ts";
export { allocationServiceDeps } from "./service.ts";
