// GENERATED by scripts/generate-page-registry.mjs — do not edit by hand.
// Regenerate after adding, moving or renaming a page; web/lib/page-registry.test.ts
// re-derives these facts from source and fails if this file has drifted.
import type { PageSpec, ViewData } from '@braedonsaunders/appkit-viewspec'

export interface PageInput {
  /** Values for the route's dynamic segments, keyed as the route names them. */
  params?: Record<string, string | undefined>
  /** The query string the page would have been visited with. */
  searchParams?: Record<string, string | undefined>
}

export interface PageModule {
  /**
   * `null` when the page renders nothing for this caller. Nine loaders
   * answer that way: they have already issued a redirect, or the reader has
   * no dashboard to show. It is an outcome, not a failure.
   */
  load: (input: PageInput) => Promise<ViewData | null>
  spec: (data: ViewData) => PageSpec
}

export interface PageRegistryEntry {
  /** The Next.js route PATTERN, matching the spec's own `route` field. */
  route: string
  /** Dynamic segments the loader needs, in route order. */
  segments: readonly string[]
  /** Whether the loader reads the query string. */
  searchParams: boolean
  /** Loaded on demand: naming a page must not import it. */
  module: () => Promise<PageModule>
}

/**
 * A required segment, or a refusal naming it.
 *
 * Thrown rather than defaulted to `''`: an empty id sends the loader looking
 * up a record that cannot exist, and the caller gets "not found" for a page
 * that is fine. Saying which segment is missing is the useful answer.
 */
export class MissingSegmentError extends Error {
  override name = 'MissingSegmentError'
  constructor(readonly segment: string) {
    super(`this route needs a value for [${segment}]`)
  }
}

function segment(input: PageInput, name: string): string {
  const value = input.params?.[name]
  if (value === undefined || value === '') throw new MissingSegmentError(name)
  return value
}

export const PAGE_REGISTRY: Readonly<Record<string, PageRegistryEntry>> = {
  '/': {
    route: '/',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/view')
      return {
        load: (input) => m.loadRootDashboard(input.searchParams ?? {}),
        spec: (data) => m.rootDashboardSpec(data as never),
      }
    },
  },
  '/accounting': {
    route: '/accounting',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/accounting/view')
      return {
        load: (input) => m.loadAccounting(input.searchParams ?? {}),
        spec: (data) => m.accountingSpec(data as never),
      }
    },
  },
  '/accounts': {
    route: '/accounts',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/accounts/view')
      return {
        load: (input) => m.loadAccounts(input.searchParams ?? {}),
        spec: (data) => m.accountsSpec(data as never),
      }
    },
  },
  '/admin': {
    route: '/admin',
    segments: [],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/admin/view')
      return {
        load: () => m.loadAdminHub(),
        spec: (data) => m.adminHubSpec(data as never),
      }
    },
  },
  '/admin/ai': {
    route: '/admin/ai',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/admin/ai/view')
      return {
        load: (input) => m.loadAdminAi(input.searchParams ?? {}),
        spec: (data) => m.adminAiSpec(data as never),
      }
    },
  },
  '/admin/api-keys': {
    route: '/admin/api-keys',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/admin/api-keys/view')
      return {
        load: (input) => m.loadApiKeys(input.searchParams ?? {}),
        spec: (data) => m.apiKeysSpec(data as never),
      }
    },
  },
  '/admin/apps': {
    route: '/admin/apps',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/admin/apps/view')
      return {
        load: (input) => m.loadAdminApps(input.searchParams ?? {}),
        spec: (data) => m.adminAppsSpec(data as never),
      }
    },
  },
  '/admin/audit': {
    route: '/admin/audit',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/admin/audit/view')
      return {
        load: (input) => m.loadAudit(input.searchParams ?? {}),
        spec: (data) => m.auditSpec(data as never),
      }
    },
  },
  '/admin/backups': {
    route: '/admin/backups',
    segments: [],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/admin/backups/view')
      return {
        load: () => m.loadAdminBackups(),
        spec: (data) => m.adminBackupsSpec(data as never),
      }
    },
  },
  '/admin/build': {
    route: '/admin/build',
    segments: [],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/admin/build/view')
      return {
        load: () => m.loadBuildHub(),
        spec: (data) => m.buildHubSpec(data as never),
      }
    },
  },
  '/admin/custom-fields': {
    route: '/admin/custom-fields',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/admin/custom-fields/view')
      return {
        load: (input) => m.loadCustomFields(input.searchParams ?? {}),
        spec: (data) => m.customFieldsSpec(data as never),
      }
    },
  },
  '/admin/customization': {
    route: '/admin/customization',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/admin/customization/view')
      return {
        load: (input) => m.loadCustomization(input.searchParams ?? {}),
        spec: (data) => m.customizationSpec(data as never),
      }
    },
  },
  '/admin/email': {
    route: '/admin/email',
    segments: [],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/admin/email/view')
      return {
        load: () => m.loadEmailSettings(),
        spec: (data) => m.emailSettingsSpec(data as never),
      }
    },
  },
  '/admin/flows': {
    route: '/admin/flows',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/admin/flows/view')
      return {
        load: (input) => m.loadFlows(input.searchParams ?? {}),
        spec: (data) => m.flowsSpec(data as never),
      }
    },
  },
  '/admin/flows/[id]': {
    route: '/admin/flows/[id]',
    segments: ['id'],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/admin/flows/[id]/view')
      return {
        load: (input) => m.loadFlowBuilder(segment(input, 'id')),
        spec: (data) => m.flowBuilderSpec(data as never),
      }
    },
  },
  '/admin/navigation': {
    route: '/admin/navigation',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/admin/navigation/view')
      return {
        load: (input) => m.loadNavigationAdmin(input.searchParams ?? {}),
        spec: (data) => m.navigationAdminSpec(data as never),
      }
    },
  },
  '/admin/pdf-templates': {
    route: '/admin/pdf-templates',
    segments: [],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/admin/pdf-templates/view')
      return {
        load: () => m.loadPdfTemplates(),
        spec: (data) => m.pdfTemplatesSpec(data as never),
      }
    },
  },
  '/admin/pdf-templates/[id]': {
    route: '/admin/pdf-templates/[id]',
    segments: ['id'],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/admin/pdf-templates/[id]/view')
      return {
        load: (input) => m.loadPdfTemplateEditor(segment(input, 'id')),
        spec: (data) => m.pdfTemplateEditorSpec(data as never),
      }
    },
  },
  '/admin/roles': {
    route: '/admin/roles',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/admin/roles/view')
      return {
        load: (input) => m.loadAdminRoles(input.searchParams ?? {}),
        spec: (data) => m.adminRolesSpec(data as never),
      }
    },
  },
  '/admin/sandboxes': {
    route: '/admin/sandboxes',
    segments: [],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/admin/sandboxes/view')
      return {
        load: () => m.loadSandboxes(),
        spec: (data) => m.sandboxesSpec(data as never),
      }
    },
  },
  '/admin/sandboxes/change-sets': {
    route: '/admin/sandboxes/change-sets',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/admin/sandboxes/change-sets/view')
      return {
        load: (input) => m.loadChangeSets(input.searchParams ?? {}),
        spec: (data) => m.changeSetsSpec(data as never),
      }
    },
  },
  '/admin/scripts': {
    route: '/admin/scripts',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/admin/scripts/view')
      return {
        load: (input) => m.loadScripts(input.searchParams ?? {}),
        spec: (data) => m.scriptsSpec(data as never),
      }
    },
  },
  '/admin/setup/[entity]': {
    route: '/admin/setup/[entity]',
    segments: ['entity'],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/admin/setup/[entity]/view')
      return {
        load: (input) => m.loadSetupEntity(segment(input, 'entity'), input.searchParams ?? {}),
        spec: (data) => m.setupEntitySpec(data as never),
      }
    },
  },
  '/admin/setup/bank-feeds': {
    route: '/admin/setup/bank-feeds',
    segments: [],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/admin/setup/bank-feeds/view')
      return {
        load: () => m.loadBankFeeds(),
        spec: (data) => m.bankFeedsSpec(data as never),
      }
    },
  },
  '/admin/setup/crm': {
    route: '/admin/setup/crm',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/admin/setup/crm/view')
      return {
        load: (input) => m.loadCrmSetup(input.searchParams ?? {}),
        spec: (data) => m.crmSetupSpec(data as never),
      }
    },
  },
  '/admin/setup/depreciation': {
    route: '/admin/setup/depreciation',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/admin/setup/depreciation/view')
      return {
        load: (input) => m.loadDepreciationSetup(input.searchParams ?? {}),
        spec: (data) => m.depreciationSetupSpec(data as never),
      }
    },
  },
  '/admin/setup/features': {
    route: '/admin/setup/features',
    segments: [],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/admin/setup/features/view')
      return {
        load: () => m.loadFeatures(),
        spec: (data) => m.featuresSpec(data as never),
      }
    },
  },
  '/admin/setup/invoicing': {
    route: '/admin/setup/invoicing',
    segments: [],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/admin/setup/invoicing/view')
      return {
        load: () => m.loadInvoicingSetup(),
        spec: (data) => m.invoicingSetupSpec(data as never),
      }
    },
  },
  '/admin/setup/labor-costing': {
    route: '/admin/setup/labor-costing',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/admin/setup/labor-costing/view')
      return {
        load: (input) => m.loadLaborCosting(input.searchParams ?? {}),
        spec: (data) => m.laborCostingSpec(data as never),
      }
    },
  },
  '/admin/setup/labor-pricing': {
    route: '/admin/setup/labor-pricing',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/admin/setup/labor-pricing/view')
      return {
        load: (input) => m.loadLaborPricing(input.searchParams ?? {}),
        spec: (data) => m.laborPricingSpec(data as never),
      }
    },
  },
  '/admin/setup/overhead': {
    route: '/admin/setup/overhead',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/admin/setup/overhead/view')
      return {
        load: (input) => m.loadOverhead(input.searchParams ?? {}),
        spec: (data) => m.overheadSpec(data as never),
      }
    },
  },
  '/admin/setup/payment-operations': {
    route: '/admin/setup/payment-operations',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/admin/setup/payment-operations/view')
      return {
        load: (input) => m.loadPaymentOperations(input.searchParams ?? {}),
        spec: (data) => m.paymentOperationsSpec(data as never),
      }
    },
  },
  '/admin/setup/payment-providers': {
    route: '/admin/setup/payment-providers',
    segments: [],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/admin/setup/payment-providers/view')
      return {
        load: () => m.loadPaymentProviders(),
        spec: (data) => m.paymentProvidersSpec(data as never),
      }
    },
  },
  '/admin/setup/payroll': {
    route: '/admin/setup/payroll',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/admin/setup/payroll/view')
      return {
        load: (input) => m.loadPayrollSetup(input.searchParams ?? {}),
        spec: (data) => m.payrollSetupSpec(data as never),
      }
    },
  },
  '/admin/setup/project-types': {
    route: '/admin/setup/project-types',
    segments: [],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/admin/setup/project-types/view')
      return {
        load: () => m.loadProjectTypes(),
        spec: (data) => m.projectTypesSpec(data as never),
      }
    },
  },
  '/admin/setup/readiness': {
    route: '/admin/setup/readiness',
    segments: [],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/admin/setup/readiness/view')
      return {
        load: () => m.loadSetupReadiness(),
        spec: (data) => m.setupReadinessSpec(data as never),
      }
    },
  },
  '/admin/setup/tax-depreciation': {
    route: '/admin/setup/tax-depreciation',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/admin/setup/tax-depreciation/view')
      return {
        load: (input) => m.loadTaxDepreciationSetup(input.searchParams ?? {}),
        spec: (data) => m.taxDepreciationSetupSpec(data as never),
      }
    },
  },
  '/admin/setup/tax-setup': {
    route: '/admin/setup/tax-setup',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/admin/setup/tax-setup/view')
      return {
        load: (input) => m.loadTaxSetup(input.searchParams ?? {}),
        spec: (data) => m.taxSetupSpec(data as never),
      }
    },
  },
  '/admin/setup/wizard': {
    route: '/admin/setup/wizard',
    segments: [],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/admin/setup/wizard/view')
      return {
        load: () => m.loadWizard(),
        spec: (data) => m.wizardSpec(data as never),
      }
    },
  },
  '/admin/users': {
    route: '/admin/users',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/admin/users/view')
      return {
        load: (input) => m.loadAdminUsers(input.searchParams ?? {}),
        spec: (data) => m.adminUsersSpec(data as never),
      }
    },
  },
  '/analytics': {
    route: '/analytics',
    segments: [],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/analytics/view')
      return {
        load: () => m.loadAnalytics(),
        spec: (data) => m.analyticsSpec(data as never),
      }
    },
  },
  '/analytics/cashflow': {
    route: '/analytics/cashflow',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/analytics/cashflow/view')
      return {
        load: (input) => m.loadCashflow(input.searchParams ?? {}),
        spec: (data) => m.cashflowSpec(data as never),
      }
    },
  },
  '/analytics/customer-intelligence': {
    route: '/analytics/customer-intelligence',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/analytics/customer-intelligence/view')
      return {
        load: (input) => m.loadCustomerIntelligence(input.searchParams ?? {}),
        spec: (data) => m.customerIntelligenceSpec(data as never),
      }
    },
  },
  '/analytics/financial-health': {
    route: '/analytics/financial-health',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/analytics/financial-health/view')
      return {
        load: (input) => m.loadFinancialHealth(input.searchParams ?? {}),
        spec: (data) => m.financialHealthSpec(data as never),
      }
    },
  },
  '/analytics/sentinel': {
    route: '/analytics/sentinel',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/analytics/sentinel/view')
      return {
        load: (input) => m.loadSentinel(input.searchParams ?? {}),
        spec: (data) => m.sentinelSpec(data as never),
      }
    },
  },
  '/analytics/spend-velocity': {
    route: '/analytics/spend-velocity',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/analytics/spend-velocity/view')
      return {
        load: (input) => m.loadSpendVelocity(input.searchParams ?? {}),
        spec: (data) => m.spendVelocitySpec(data as never),
      }
    },
  },
  '/analytics/true-cost/planner': {
    route: '/analytics/true-cost/planner',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/analytics/true-cost/planner/view')
      return {
        load: (input) => m.loadTrueCostPlanner(input.searchParams ?? {}),
        spec: (data) => m.trueCostPlannerSpec(data as never),
      }
    },
  },
  '/analytics/utilization': {
    route: '/analytics/utilization',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/analytics/utilization/view')
      return {
        load: (input) => m.loadUtilization(input.searchParams ?? {}),
        spec: (data) => m.utilizationSpec(data as never),
      }
    },
  },
  '/analytics/vendor-performance': {
    route: '/analytics/vendor-performance',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/analytics/vendor-performance/view')
      return {
        load: (input) => m.loadVendorPerformance(input.searchParams ?? {}),
        spec: (data) => m.vendorPerformanceSpec(data as never),
      }
    },
  },
  '/ap': {
    route: '/ap',
    segments: [],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/ap/view')
      return {
        load: () => m.loadApCockpit(),
        spec: (data) => m.apCockpitSpec(data as never),
      }
    },
  },
  '/ap/bills': {
    route: '/ap/bills',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/ap/bills/view')
      return {
        load: (input) => m.loadApBills(input.searchParams ?? {}),
        spec: (data) => m.apBillsSpec(data as never),
      }
    },
  },
  '/ap/capture': {
    route: '/ap/capture',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/ap/capture/view')
      return {
        load: (input) => m.loadApCapture(input.searchParams ?? {}),
        spec: (data) => m.apCaptureSpec(data as never),
      }
    },
  },
  '/api-docs': {
    route: '/api-docs',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/api-docs/view')
      return {
        load: (input) => m.loadApiDocs(input.searchParams ?? {}),
        spec: (data) => m.apiDocsSpec(data as never),
      }
    },
  },
  '/approvals': {
    route: '/approvals',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/approvals/view')
      return {
        load: (input) => m.loadApprovals(input.searchParams ?? {}),
        spec: (data) => m.approvalsSpec(data as never),
      }
    },
  },
  '/apps': {
    route: '/apps',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/apps/view')
      return {
        load: (input) => m.loadAppsLauncher(input.searchParams ?? {}),
        spec: (data) => m.appsLauncherSpec(data as never),
      }
    },
  },
  '/apps/[key]': {
    route: '/apps/[key]',
    segments: ['key'],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/apps/[key]/view')
      return {
        load: (input) => m.loadAppRuntime(segment(input, 'key')),
        spec: (data) => m.appRuntimeSpec(data as never),
      }
    },
  },
  '/apps/library': {
    route: '/apps/library',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/apps/library/view')
      return {
        load: (input) => m.loadAppsLibrary(input.searchParams ?? {}),
        spec: (data) => m.appsLibrarySpec(data as never),
      }
    },
  },
  '/ar': {
    route: '/ar',
    segments: [],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/ar/view')
      return {
        load: () => m.loadArCockpit(),
        spec: (data) => m.arCockpitSpec(data as never),
      }
    },
  },
  '/ar/invoices': {
    route: '/ar/invoices',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/ar/invoices/view')
      return {
        load: (input) => m.loadArInvoices(input.searchParams ?? {}),
        spec: (data) => m.arInvoicesSpec(data as never),
      }
    },
  },
  '/assets': {
    route: '/assets',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/assets/view')
      return {
        load: (input) => m.loadAssets(input.searchParams ?? {}),
        spec: (data) => m.assetsSpec(data as never),
      }
    },
  },
  '/assets/equipment': {
    route: '/assets/equipment',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/assets/equipment/view')
      return {
        load: (input) => m.loadEquipmentPage(input.searchParams ?? {}),
        spec: (data) => m.equipmentSpec(data as never),
      }
    },
  },
  '/assistant': {
    route: '/assistant',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/assistant/view')
      return {
        load: (input) => m.loadAssistant(input.searchParams ?? {}),
        spec: (data) => m.assistantSpec(data as never),
      }
    },
  },
  '/assistant/[id]': {
    route: '/assistant/[id]',
    segments: ['id'],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/assistant/[id]/view')
      return {
        load: (input) => m.loadAssistantConversation(segment(input, 'id')),
        spec: (data) => m.assistantConversationSpec(data as never),
      }
    },
  },
  '/banking': {
    route: '/banking',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/banking/view')
      return {
        load: (input) => m.loadBanking(input.searchParams ?? {}),
        spec: (data) => m.bankingSpec(data as never),
      }
    },
  },
  '/banking/[accountId]': {
    route: '/banking/[accountId]',
    segments: ['accountId'],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/banking/[accountId]/view')
      return {
        load: (input) => m.loadBankingAccount(segment(input, 'accountId'), input.searchParams ?? {}),
        spec: (data) => m.bankingAccountSpec(data as never),
      }
    },
  },
  '/banking/[accountId]/reconcile/[reconciliationId]': {
    route: '/banking/[accountId]/reconcile/[reconciliationId]',
    segments: ['accountId', 'reconciliationId'],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/banking/[accountId]/reconcile/[reconciliationId]/view')
      return {
        load: (input) => m.loadReconciliation(segment(input, 'accountId'), segment(input, 'reconciliationId'), input.searchParams ?? {}),
        spec: (data) => m.reconcileSpec(data as never),
      }
    },
  },
  '/banking/cash': {
    route: '/banking/cash',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/banking/cash/view')
      return {
        load: (input) => m.loadBankingCash(input.searchParams ?? {}),
        spec: (data) => m.bankingCashSpec(data as never),
      }
    },
  },
  '/banking/imports': {
    route: '/banking/imports',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/banking/imports/view')
      return {
        load: (input) => m.loadBankingImports(input.searchParams ?? {}),
        spec: (data) => m.bankingImportsSpec(data as never),
      }
    },
  },
  '/banking/match': {
    route: '/banking/match',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/banking/match/view')
      return {
        load: (input) => m.loadMatch(input.searchParams ?? {}),
        spec: (data) => m.matchSpec(data as never),
      }
    },
  },
  '/banking/psp-settlements': {
    route: '/banking/psp-settlements',
    segments: [],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/banking/psp-settlements/view')
      return {
        load: () => m.loadPspSettlements(),
        spec: (data) => m.pspSettlementsSpec(data as never),
      }
    },
  },
  '/banking/reconciliations': {
    route: '/banking/reconciliations',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/banking/reconciliations/view')
      return {
        load: (input) => m.loadBankingReconciliations(input.searchParams ?? {}),
        spec: (data) => m.bankingReconciliationsSpec(data as never),
      }
    },
  },
  '/banking/rules': {
    route: '/banking/rules',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/banking/rules/view')
      return {
        load: (input) => m.loadBankingRules(input.searchParams ?? {}),
        spec: (data) => m.bankingRulesSpec(data as never),
      }
    },
  },
  '/banking/transactions': {
    route: '/banking/transactions',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/banking/transactions/view')
      return {
        load: (input) => m.loadBankingTransactions(input.searchParams ?? {}),
        spec: (data) => m.bankingTransactionsSpec(data as never),
      }
    },
  },
  '/budgets': {
    route: '/budgets',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/budgets/view')
      return {
        load: (input) => m.loadBudgets(input.searchParams ?? {}),
        spec: (data) => m.budgetsSpec(data as never),
      }
    },
  },
  '/close': {
    route: '/close',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/close/view')
      return {
        load: (input) => m.loadClose(input.searchParams ?? {}),
        spec: (data) => m.closeSpec(data as never),
      }
    },
  },
  '/collections': {
    route: '/collections',
    segments: [],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/collections/view')
      return {
        load: () => m.loadCollections(),
        spec: (data) => m.collectionsSpec(data as never),
      }
    },
  },
  '/compliance': {
    route: '/compliance',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/compliance/view')
      return {
        load: (input) => m.loadCompliance(input.searchParams ?? {}),
        spec: (data) => m.complianceSpec(data as never),
      }
    },
  },
  '/compliance/information-returns': {
    route: '/compliance/information-returns',
    segments: [],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/compliance/information-returns/view')
      return {
        load: () => m.loadInformationReturns(),
        spec: (data) => m.informationReturnsSpec(data as never),
      }
    },
  },
  '/compliance/information-returns/[id]': {
    route: '/compliance/information-returns/[id]',
    segments: ['id'],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/compliance/information-returns/[id]/view')
      return {
        load: (input) => m.loadFilingDetail(segment(input, 'id')),
        spec: (data) => m.filingDetailSpec(data as never),
      }
    },
  },
  '/compliance/lien-waivers': {
    route: '/compliance/lien-waivers',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/compliance/lien-waivers/view')
      return {
        load: (input) => m.loadLienWaiversPage(input.searchParams ?? {}),
        spec: (data) => m.lienWaiversSpec(data as never),
      }
    },
  },
  '/compliance/vendors': {
    route: '/compliance/vendors',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/compliance/vendors/view')
      return {
        load: (input) => m.loadComplianceVendors(input.searchParams ?? {}),
        spec: (data) => m.complianceVendorsSpec(data as never),
      }
    },
  },
  '/continuous-close': {
    route: '/continuous-close',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/continuous-close/view')
      return {
        load: (input) => m.loadContinuousClose(input.searchParams ?? {}),
        spec: (data) => m.continuousCloseSpec(data as never),
      }
    },
  },
  '/crm/activities': {
    route: '/crm/activities',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/crm/activities/view')
      return {
        load: (input) => m.loadActivities(input.searchParams ?? {}),
        spec: (data) => m.activitiesSpec(data as never),
      }
    },
  },
  '/crm/forecasts': {
    route: '/crm/forecasts',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/crm/forecasts/view')
      return {
        load: (input) => m.loadForecasts(input.searchParams ?? {}),
        spec: (data) => m.forecastsSpec(data as never),
      }
    },
  },
  '/crm/leads': {
    route: '/crm/leads',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/crm/leads/view')
      return {
        load: (input) => m.loadLeads(input.searchParams ?? {}),
        spec: (data) => m.leadsSpec(data as never),
      }
    },
  },
  '/crm/opportunities': {
    route: '/crm/opportunities',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/crm/opportunities/view')
      return {
        load: (input) => m.loadOpportunities(input.searchParams ?? {}),
        spec: (data) => m.opportunitiesSpec(data as never),
      }
    },
  },
  '/crm/prospects': {
    route: '/crm/prospects',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/crm/prospects/view')
      return {
        load: (input) => m.loadProspects(input.searchParams ?? {}),
        spec: (data) => m.prospectsSpec(data as never),
      }
    },
  },
  '/customers': {
    route: '/customers',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/customers/view')
      return {
        load: (input) => m.loadCustomers(input.searchParams ?? {}),
        spec: (data) => m.customersSpec(data as never),
      }
    },
  },
  '/dashboard': {
    route: '/dashboard',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/dashboard/view')
      return {
        load: (input) => m.loadDashboard(input.searchParams ?? {}),
        spec: (data) => m.dashboardSpec(data as never),
      }
    },
  },
  '/dashboard/customize': {
    route: '/dashboard/customize',
    segments: [],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/dashboard/customize/view')
      return {
        load: () => m.loadCustomizeDashboard(),
        spec: (data) => m.customizeDashboardSpec(data as never),
      }
    },
  },
  '/data/export': {
    route: '/data/export',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/data/export/view')
      return {
        load: (input) => m.loadDataExport(input.searchParams ?? {}),
        spec: (data) => m.dataExportSpec(data as never),
      }
    },
  },
  '/data/import': {
    route: '/data/import',
    segments: [],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/data/import/view')
      return {
        load: () => m.loadDataImport(),
        spec: () => m.dataImportSpec(),
      }
    },
  },
  '/data/import/history': {
    route: '/data/import/history',
    segments: [],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/data/import/history/view')
      return {
        load: () => m.loadImportHistory(),
        spec: () => m.importHistorySpec(),
      }
    },
  },
  '/docs': {
    route: '/docs',
    segments: [],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/docs/view')
      return {
        load: () => m.loadDocsHome(),
        spec: (data) => m.docsHomeSpec(data as never),
      }
    },
  },
  '/docs/[slug]': {
    route: '/docs/[slug]',
    segments: ['slug'],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/docs/[slug]/view')
      return {
        load: (input) => m.loadDocArticle(segment(input, 'slug')),
        spec: (data) => m.docArticleSpec(data as never),
      }
    },
  },
  '/documents': {
    route: '/documents',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/documents/view')
      return {
        load: (input) => m.loadDocuments(input.searchParams ?? {}),
        spec: (data) => m.documentsSpec(data as never),
      }
    },
  },
  '/documents/trash': {
    route: '/documents/trash',
    segments: [],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/documents/trash/view')
      return {
        load: () => m.loadTrash(),
        spec: (data) => m.trashSpec(data as never),
      }
    },
  },
  '/entities/[role]': {
    route: '/entities/[role]',
    segments: ['role'],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/entities/[role]/view')
      return {
        load: (input) => m.loadEntityRole(segment(input, 'role'), input.searchParams ?? {}),
        spec: (data) => m.entityRoleSpec(data as never),
      }
    },
  },
  '/estimates': {
    route: '/estimates',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/estimates/view')
      return {
        load: (input) => m.loadEstimates(input.searchParams ?? {}),
        spec: (data) => m.estimatesSpec(data as never),
      }
    },
  },
  '/expenses': {
    route: '/expenses',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/expenses/view')
      return {
        load: (input) => m.loadExpenses(input.searchParams ?? {}),
        spec: (data) => m.expensesSpec(data as never),
      }
    },
  },
  '/expenses/reports': {
    route: '/expenses/reports',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/expenses/reports/view')
      return {
        load: (input) => m.loadExpenseReports(input.searchParams ?? {}),
        spec: (data) => m.expenseReportsSpec(data as never),
      }
    },
  },
  '/field-tickets': {
    route: '/field-tickets',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/field-tickets/view')
      return {
        load: (input) => m.loadFieldTickets(input.searchParams ?? {}),
        spec: (data) => m.fieldTicketsSpec(data as never),
      }
    },
  },
  '/insights': {
    route: '/insights',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/insights/view')
      return {
        load: (input) => m.loadInsights(input.searchParams ?? {}),
        spec: (data) => m.insightsSpec(data as never),
      }
    },
  },
  '/insights/dashboards': {
    route: '/insights/dashboards',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/insights/dashboards/view')
      return {
        load: (input) => m.loadDashboards(input.searchParams ?? {}),
        spec: (data) => m.dashboardsSpec(data as never),
      }
    },
  },
  '/insights/dashboards/[id]': {
    route: '/insights/dashboards/[id]',
    segments: ['id'],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/insights/dashboards/[id]/view')
      return {
        load: (input) => m.loadInsightsDashboard(segment(input, 'id')),
        spec: (data) => m.insightsDashboardSpec(data as never),
      }
    },
  },
  '/inventory': {
    route: '/inventory',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/inventory/view')
      return {
        load: (input) => m.loadInventory(input.searchParams ?? {}),
        spec: (data) => m.inventorySpec(data as never),
      }
    },
  },
  '/items': {
    route: '/items',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/items/view')
      return {
        load: (input) => m.loadItems(input.searchParams ?? {}),
        spec: (data) => m.itemsSpec(data as never),
      }
    },
  },
  '/journal': {
    route: '/journal',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/journal/view')
      return {
        load: (input) => m.loadJournal(input.searchParams ?? {}),
        spec: (data) => m.journalSpec(data as never),
      }
    },
  },
  '/knowledge/views': {
    route: '/knowledge/views',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/knowledge/views/view')
      return {
        load: (input) => m.loadViewsPage(input.searchParams ?? {}),
        spec: (data) => m.viewsSpec(data as never),
      }
    },
  },
  '/knowledge/views/[id]': {
    route: '/knowledge/views/[id]',
    segments: ['id'],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/knowledge/views/[id]/view')
      return {
        load: (input) => m.loadSavedViewRun({ id: segment(input, 'id') }, input.searchParams ?? {}),
        spec: (data) => m.savedViewRunSpec(data as never),
      }
    },
  },
  '/parties': {
    route: '/parties',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/parties/view')
      return {
        load: (input) => m.loadParties(input.searchParams ?? {}),
        spec: (data) => m.partiesSpec(data as never),
      }
    },
  },
  '/payments': {
    route: '/payments',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/payments/view')
      return {
        load: (input) => m.loadPayments(input.searchParams ?? {}),
        spec: (data) => m.paymentsSpec(data as never),
      }
    },
  },
  '/payroll': {
    route: '/payroll',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/payroll/view')
      return {
        load: (input) => m.loadPayroll(input.searchParams ?? {}),
        spec: (data) => m.payrollSpec(data as never),
      }
    },
  },
  '/payroll/opening-balances': {
    route: '/payroll/opening-balances',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/payroll/opening-balances/view')
      return {
        load: (input) => m.loadPayrollOpeningBalances(input.searchParams ?? {}),
        spec: (data) => m.payrollOpeningBalancesSpec(data as never),
      }
    },
  },
  '/payroll/parallel-run': {
    route: '/payroll/parallel-run',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/payroll/parallel-run/view')
      return {
        load: (input) => m.loadParallelRun(input.searchParams ?? {}),
        spec: (data) => m.parallelRunSpec(data as never),
      }
    },
  },
  '/payroll/remittances': {
    route: '/payroll/remittances',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/payroll/remittances/view')
      return {
        load: (input) => m.loadRemittances(input.searchParams ?? {}),
        spec: (data) => m.remittancesSpec(data as never),
      }
    },
  },
  '/payroll/retro': {
    route: '/payroll/retro',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/payroll/retro/view')
      return {
        load: (input) => m.loadPayrollRetro(input.searchParams ?? {}),
        spec: (data) => m.payrollRetroSpec(data as never),
      }
    },
  },
  '/payroll/runs': {
    route: '/payroll/runs',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/payroll/runs/view')
      return {
        load: (input) => m.loadPayRuns(input.searchParams ?? {}),
        spec: (data) => m.payRunsSpec(data as never),
      }
    },
  },
  '/payroll/runs/[id]': {
    route: '/payroll/runs/[id]',
    segments: ['id'],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/payroll/runs/[id]/view')
      return {
        load: (input) => m.loadPayRunWizard(segment(input, 'id'), input.searchParams ?? {}),
        spec: (data) => m.payRunWizardSpec(data as never),
      }
    },
  },
  '/payroll/separations': {
    route: '/payroll/separations',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/payroll/separations/view')
      return {
        load: (input) => m.loadSeparations(input.searchParams ?? {}),
        spec: (data) => m.separationsSpec(data as never),
      }
    },
  },
  '/payroll/year-end': {
    route: '/payroll/year-end',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/payroll/year-end/view')
      return {
        load: (input) => m.loadYearEnd(input.searchParams ?? {}),
        spec: (data) => m.yearEndSpec(data as never),
      }
    },
  },
  '/platform': {
    route: '/platform',
    segments: [],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/platform/view')
      return {
        load: () => m.loadPlatformHub(),
        spec: (data) => m.platformHubSpec(data as never),
      }
    },
  },
  '/platform/access': {
    route: '/platform/access',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/platform/access/view')
      return {
        load: (input) => m.loadPlatformAccess(input.searchParams ?? {}),
        spec: (data) => m.platformAccessSpec(data as never),
      }
    },
  },
  '/platform/email-log': {
    route: '/platform/email-log',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/platform/email-log/view')
      return {
        load: (input) => m.loadEmailLog(input.searchParams ?? {}),
        spec: (data) => m.emailLogSpec(data as never),
      }
    },
  },
  '/platform/organizations': {
    route: '/platform/organizations',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/platform/organizations/view')
      return {
        load: (input) => m.loadPlatformOrganizations(input.searchParams ?? {}),
        spec: (data) => m.platformOrganizationsSpec(data as never),
      }
    },
  },
  '/platform/users': {
    route: '/platform/users',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/platform/users/view')
      return {
        load: (input) => m.loadPlatformUsers(input.searchParams ?? {}),
        spec: (data) => m.platformUsersSpec(data as never),
      }
    },
  },
  '/platform/users/[id]': {
    route: '/platform/users/[id]',
    segments: ['id'],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/platform/users/[id]/view')
      return {
        load: (input) => m.loadPlatformUser(segment(input, 'id')),
        spec: (data) => m.platformUserSpec(data as never),
      }
    },
  },
  '/projects': {
    route: '/projects',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/projects/view')
      return {
        load: (input) => m.loadProjects(input.searchParams ?? {}),
        spec: (data) => m.projectsSpec(data as never),
      }
    },
  },
  '/projects/wip-billing': {
    route: '/projects/wip-billing',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/projects/wip-billing/view')
      return {
        load: (input) => m.loadWipBilling(input.searchParams ?? {}),
        spec: (data) => m.wipBillingSpec(data as never),
      }
    },
  },
  '/property-management': {
    route: '/property-management',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/property-management/view')
      return {
        load: (input) => m.loadPropertyManagement(input.searchParams ?? {}),
        spec: (data) => m.propertyManagementSpec(data as never),
      }
    },
  },
  '/purchase-orders': {
    route: '/purchase-orders',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/purchase-orders/view')
      return {
        load: (input) => m.loadPurchaseOrders(input.searchParams ?? {}),
        spec: (data) => m.purchaseOrdersSpec(data as never),
      }
    },
  },
  '/purchasing': {
    route: '/purchasing',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/purchasing/view')
      return {
        load: (input) => m.loadPurchasing(input.searchParams ?? {}),
        spec: (data) => m.purchasingSpec(data as never),
      }
    },
  },
  '/query': {
    route: '/query',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/query/view')
      return {
        load: (input) => m.loadQuery(input.searchParams ?? {}),
        spec: (data) => m.querySpec(data as never),
      }
    },
  },
  '/receipts': {
    route: '/receipts',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/receipts/view')
      return {
        load: (input) => m.loadReceipts(input.searchParams ?? {}),
        spec: (data) => m.receiptsSpec(data as never),
      }
    },
  },
  '/records/[typeKey]': {
    route: '/records/[typeKey]',
    segments: ['typeKey'],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/records/[typeKey]/view')
      return {
        load: (input) => m.loadRecordModule(input.searchParams ?? {}, segment(input, 'typeKey')),
        spec: (data) => m.recordModuleSpec(data as never),
      }
    },
  },
  '/records/types': {
    route: '/records/types',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/records/types/view')
      return {
        load: (input) => m.loadRecordTypes(input.searchParams ?? {}),
        spec: (data) => m.recordTypesSpec(data as never),
      }
    },
  },
  '/reports': {
    route: '/reports',
    segments: [],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/reports/view')
      return {
        load: () => m.loadReportsHub(),
        spec: (data) => m.reportsHubSpec(data as never),
      }
    },
  },
  '/reports/aging': {
    route: '/reports/aging',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/reports/aging/view')
      return {
        load: (input) => m.loadAging(input.searchParams ?? {}),
        spec: (data) => m.agingSpec(data as never),
      }
    },
  },
  '/reports/balance-sheet': {
    route: '/reports/balance-sheet',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/reports/balance-sheet/view')
      return {
        load: (input) => m.loadBalanceSheet(input.searchParams ?? {}),
        spec: (data) => m.balanceSheetSpec(data as never),
      }
    },
  },
  '/reports/budget': {
    route: '/reports/budget',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/reports/budget/view')
      return {
        load: (input) => m.loadBudgetReport(input.searchParams ?? {}),
        spec: (data) => m.budgetReportSpec(data as never),
      }
    },
  },
  '/reports/cash-flow': {
    route: '/reports/cash-flow',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/reports/cash-flow/view')
      return {
        load: (input) => m.loadCashFlow(input.searchParams ?? {}),
        spec: (data) => m.cashFlowSpec(data as never),
      }
    },
  },
  '/reports/cash-flow-indirect': {
    route: '/reports/cash-flow-indirect',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/reports/cash-flow-indirect/view')
      return {
        load: (input) => m.loadCashFlowIndirect(input.searchParams ?? {}),
        spec: (data) => m.cashFlowIndirectSpec(data as never),
      }
    },
  },
  '/reports/custom': {
    route: '/reports/custom',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/reports/custom/view')
      return {
        load: (input) => m.loadCustomReports(input.searchParams ?? {}),
        spec: (data) => m.customReportsSpec(data as never),
      }
    },
  },
  '/reports/custom/builder/[id]': {
    route: '/reports/custom/builder/[id]',
    segments: ['id'],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/reports/custom/builder/[id]/view')
      return {
        load: (input) => m.loadReportBuilder(segment(input, 'id')),
        spec: (data) => m.reportBuilderSpec(data as never),
      }
    },
  },
  '/reports/custom/run/[id]': {
    route: '/reports/custom/run/[id]',
    segments: ['id'],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/reports/custom/run/[id]/view')
      return {
        load: (input) => m.loadReportRun(segment(input, 'id'), input.searchParams ?? {}),
        spec: (data) => m.reportRunSpec(data as never),
      }
    },
  },
  '/reports/custom/run/[id]/delivery': {
    route: '/reports/custom/run/[id]/delivery',
    segments: ['id'],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/reports/custom/run/[id]/delivery/view')
      return {
        load: (input) => m.loadReportDelivery(segment(input, 'id')),
        spec: (data) => m.reportDeliverySpec(data as never),
      }
    },
  },
  '/reports/general-ledger': {
    route: '/reports/general-ledger',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/reports/general-ledger/view')
      return {
        load: (input) => m.loadGeneralLedger(input.searchParams ?? {}),
        spec: (data) => m.generalLedgerSpec(data as never),
      }
    },
  },
  '/reports/journal': {
    route: '/reports/journal',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/reports/journal/view')
      return {
        load: (input) => m.loadJournal(input.searchParams ?? {}),
        spec: (data) => m.journalSpec(data as never),
      }
    },
  },
  '/reports/orders': {
    route: '/reports/orders',
    segments: [],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/reports/orders/view')
      return {
        load: () => m.loadOrders(),
        spec: () => m.ordersSpec(),
      }
    },
  },
  '/reports/partners': {
    route: '/reports/partners',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/reports/partners/view')
      return {
        load: (input) => m.loadPartners(input.searchParams ?? {}),
        spec: (data) => m.partnersSpec(data as never),
      }
    },
  },
  '/reports/pnl': {
    route: '/reports/pnl',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/reports/pnl/view')
      return {
        load: (input) => m.loadPnl(input.searchParams ?? {}),
        spec: (data) => m.pnlSpec(data as never),
      }
    },
  },
  '/reports/project-profitability': {
    route: '/reports/project-profitability',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/reports/project-profitability/view')
      return {
        load: (input) => m.loadProjectProfitability(input.searchParams ?? {}),
        spec: (data) => m.projectProfitabilitySpec(data as never),
      }
    },
  },
  '/reports/registers': {
    route: '/reports/registers',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/reports/registers/view')
      return {
        load: (input) => m.loadRegisters(input.searchParams ?? {}),
        spec: (data) => m.registersSpec(data as never),
      }
    },
  },
  '/reports/statements/[partyId]': {
    route: '/reports/statements/[partyId]',
    segments: ['partyId'],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/reports/statements/[partyId]/view')
      return {
        load: (input) => m.loadStatement(segment(input, 'partyId'), input.searchParams ?? {}),
        spec: (data) => m.statementSpec(data as never),
      }
    },
  },
  '/reports/trial-balance': {
    route: '/reports/trial-balance',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/reports/trial-balance/view')
      return {
        load: (input) => m.loadTrialBalance(input.searchParams ?? {}),
        spec: (data) => m.trialBalanceSpec(data as never),
      }
    },
  },
  '/reports/true-cost': {
    route: '/reports/true-cost',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/reports/true-cost/view')
      return {
        load: (input) => m.loadTrueCost(input.searchParams ?? {}),
        spec: (data) => m.trueCostSpec(data as never),
      }
    },
  },
  '/revenue': {
    route: '/revenue',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/revenue/view')
      return {
        load: (input) => m.loadRevenue(input.searchParams ?? {}),
        spec: (data) => m.revenueSpec(data as never),
      }
    },
  },
  '/sales-orders': {
    route: '/sales-orders',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/sales-orders/view')
      return {
        load: (input) => m.loadSalesOrders(input.searchParams ?? {}),
        spec: (data) => m.salesOrdersSpec(data as never),
      }
    },
  },
  '/settings/security': {
    route: '/settings/security',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/settings/security/view')
      return {
        load: (input) => m.loadSecurity(input.searchParams ?? {}),
        spec: (data) => m.securitySpec(data as never),
      }
    },
  },
  '/subcontracts': {
    route: '/subcontracts',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/subcontracts/view')
      return {
        load: (input) => m.loadSubcontracts(input.searchParams ?? {}),
        spec: (data) => m.subcontractsSpec(data as never),
      }
    },
  },
  '/sync': {
    route: '/sync',
    segments: [],
    searchParams: false,
    module: async () => {
      const m = await import('../app/(app)/sync/view')
      return {
        load: () => m.loadSync(),
        spec: (data) => m.syncSpec(data as never),
      }
    },
  },
  '/tax': {
    route: '/tax',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/tax/view')
      return {
        load: (input) => m.loadTax(input.searchParams ?? {}),
        spec: (data) => m.taxSpec(data as never),
      }
    },
  },
  '/tax/provisions': {
    route: '/tax/provisions',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/tax/provisions/view')
      return {
        load: (input) => m.loadTaxProvisions(input.searchParams ?? {}),
        spec: (data) => m.taxProvisionsSpec(data as never),
      }
    },
  },
  '/tax/provisions/[id]': {
    route: '/tax/provisions/[id]',
    segments: ['id'],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/tax/provisions/[id]/view')
      return {
        load: (input) => m.loadProvisionDetail(input.searchParams ?? {}, segment(input, 'id')),
        spec: (data) => m.provisionDetailSpec(data as never),
      }
    },
  },
  '/timesheets': {
    route: '/timesheets',
    segments: [],
    searchParams: true,
    module: async () => {
      const m = await import('../app/(app)/timesheets/view')
      return {
        load: (input) => m.loadTimesheets(input.searchParams ?? {}),
        spec: (data) => m.timesheetsSpec(data as never),
      }
    },
  },
}

/** Every route that has a built-in layout, sorted. */
export const PAGE_ROUTES: readonly string[] = Object.keys(PAGE_REGISTRY).sort()
