// GENERATED by scripts/payroll-new-tax-year.ts from the rates-<year>.ts modules
// present in this directory. Do not edit by hand — add a year by running the
// scaffold, then transcribe the published TP-1015.F-V figures into the year
// module.
import type { QcEditionRates } from "./rates.ts";

export const QC_EXTRA_EDITIONS: readonly QcEditionRates[] = [];
