import {
  Activity,
  AlertTriangle,
  BarChart3,
  Bell,
  BookOpen,
  Calendar,
  Camera,
  CheckCircle2,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cog,
  Download,
  Droplet,
  FileCheck,
  FileText,
  Flag,
  Flame,
  Folder,
  Gauge,
  GraduationCap,
  Hammer,
  HardHat,
  HeartPulse,
  Image as ImageIcon,
  Key,
  Link2,
  ListChecks,
  Lock,
  Mail,
  Map as MapIcon,
  MapPin,
  NotebookPen,
  Package,
  PenLine,
  Phone,
  PlayCircle,
  Plus,
  Radiation,
  Receipt,
  Search,
  Settings,
  ShieldAlert,
  ShieldCheck,
  Siren,
  Star,
  Thermometer,
  TrafficCone,
  Truck,
  Upload,
  User,
  Users,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react'

export const ICON_PICKER_KEYS = [
  'zap',
  'plus',
  'alert',
  'shield-alert',
  'shield',
  'siren',
  'radiation',
  'flame',
  'droplet',
  'hard-hat',
  'traffic-cone',
  'hammer',
  'wrench',
  'cog',
  'clipboard',
  'clipboard-check',
  'list-checks',
  'check',
  'file',
  'file-check',
  'folder',
  'book',
  'grad',
  'journal',
  'pencil',
  'users',
  'user',
  'pin',
  'map',
  'truck',
  'box',
  'gauge',
  'activity',
  'chart',
  'bell',
  'calendar',
  'clock',
  'camera',
  'image',
  'phone',
  'mail',
  'link',
  'search',
  'settings',
  'star',
  'flag',
  'heart',
  'thermometer',
  'key',
  'lock',
  'play',
  'download',
  'upload',
  'receipt',
] as const

export const QUICK_ACTION_ICONS: Record<string, LucideIcon> = {
  zap: Zap,
  plus: Plus,
  alert: AlertTriangle,
  'shield-alert': ShieldAlert,
  shield: ShieldCheck,
  siren: Siren,
  radiation: Radiation,
  flame: Flame,
  droplet: Droplet,
  'hard-hat': HardHat,
  'traffic-cone': TrafficCone,
  hammer: Hammer,
  wrench: Wrench,
  cog: Cog,
  clipboard: ClipboardList,
  'clipboard-check': ClipboardCheck,
  'list-checks': ListChecks,
  check: CheckCircle2,
  file: FileText,
  'file-check': FileCheck,
  folder: Folder,
  book: BookOpen,
  grad: GraduationCap,
  journal: NotebookPen,
  pencil: PenLine,
  users: Users,
  user: User,
  pin: MapPin,
  map: MapIcon,
  truck: Truck,
  box: Package,
  gauge: Gauge,
  activity: Activity,
  chart: BarChart3,
  bell: Bell,
  calendar: Calendar,
  clock: Clock,
  camera: Camera,
  image: ImageIcon,
  phone: Phone,
  mail: Mail,
  link: Link2,
  search: Search,
  settings: Settings,
  star: Star,
  flag: Flag,
  heart: HeartPulse,
  thermometer: Thermometer,
  key: Key,
  lock: Lock,
  play: PlayCircle,
  download: Download,
  upload: Upload,
  receipt: Receipt,
  // Aliases for sidebar / form-template icon keys
  'circle-user': User,
  message: Mail,
  timer: Clock,
  library: BookOpen,
  construction: TrafficCone,
  award: Star,
  rss: Activity,
  'list-check': ListChecks,
  graduation: GraduationCap,
}

export const FALLBACK_ICON: LucideIcon = Zap
