// GENERATED by scripts/payroll-new-tax-year.ts from the rates-<year>.ts modules
// present in this directory. Do not edit by hand — add a year by running the
// scaffold, then transcribe the published figures into the year module.
import { RATES_2024 } from "./rates-2024.ts";
import { RATES_2025 } from "./rates-2025.ts";
import type { YearRates } from "./rates.ts";

export const US_EXTRA_EDITIONS: readonly YearRates[] = [
  RATES_2024,
  RATES_2025,
];
