// GENERATED by scripts/payroll-new-tax-year.ts from the rates-<year>.ts modules
// present in this directory. Do not edit by hand — add a year by running the
// scaffold, then transcribe the published figures into the year module.
import type { YearRates } from "./rates.ts";

export const US_EXTRA_EDITIONS: readonly YearRates[] = [];
