import type { TaxReturnPack } from "./types.ts";

export const CANADA_RETURN_PACKS: readonly TaxReturnPack[] = [
  {
    code: "CA_GST34", name: "GST/HST Return (GST34)", country: "CA",
    jurisdiction: { code: "CA", name: "Canada", country: "CA", level: "country", taxType: "gst" },
    defaultFrequency: "quarterly", submissionChannel: "portal_manual", governmentFormat: "portal_entry",
    submissionUrl: "https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/gst-hst-businesses/file-gst-hst-return/how-file.html",
    watermark: "Working copy — submit electronically through the government filing service",
    boxes: [
      { lineCode: "101", label: "Sales and other revenue", sign: 1, sequence: 10, basis: "taxable_base", glMap: "sales" },
      { lineCode: "103", label: "GST/HST collected or collectible", sign: -1, sequence: 20, basis: "tax_collected", glMap: "sales" },
      { lineCode: "104", label: "Adjustments to be added to net tax", sign: 1, sequence: 30 },
      { lineCode: "105", label: "Total GST/HST and adjustments (add lines 103 and 104)", sign: 1, sequence: 40, formula: "103 + 104" },
      { lineCode: "106", label: "Input tax credits (ITCs)", sign: 1, sequence: 50, basis: "tax_paid", glMap: "purchases" },
      { lineCode: "107", label: "Adjustments to be deducted from net tax", sign: 1, sequence: 60 },
      { lineCode: "108", label: "Total ITCs and adjustments (add lines 106 and 107)", sign: 1, sequence: 70, formula: "106 + 107" },
      { lineCode: "109", label: "Net tax (subtract line 108 from line 105)", sign: 1, sequence: 80, formula: "105 - 108" },
      { lineCode: "110", label: "Instalment and other annual filer payments", sign: 1, sequence: 90 },
      { lineCode: "111", label: "Rebates (attach the rebate form to this return)", sign: 1, sequence: 100 },
      { lineCode: "112", label: "Total other credits (add lines 110 and 111)", sign: 1, sequence: 110, formula: "110 + 111" },
      { lineCode: "113A", label: "Balance (subtract line 112 from line 109)", sign: 1, sequence: 120, formula: "109 - 112" },
      { lineCode: "205", label: "GST/HST due on the acquisition of taxable real property", sign: 1, sequence: 130 },
      { lineCode: "405", label: "Other GST/HST to be self-assessed", sign: 1, sequence: 140 },
      { lineCode: "113B", label: "Total other debits (add lines 205 and 405)", sign: 1, sequence: 150, formula: "205 + 405" },
      { lineCode: "113C", label: "Balance (add lines 113A and 113B)", sign: 1, sequence: 160, formula: "113A + 113B" },
      { lineCode: "114", label: "Refund claimed", sign: 1, sequence: 170, formula: "max(-113C, 0)" },
      { lineCode: "115", label: "Payment enclosed", sign: 1, sequence: 180, formula: "max(113C, 0)" },
    ],
  },
  {
    code: "CA_BC_PST", name: "British Columbia PST Return", country: "CA",
    jurisdiction: { code: "CA-BC", name: "British Columbia", country: "CA", region: "BC", level: "state", taxType: "pst" },
    defaultFrequency: "monthly", submissionChannel: "portal_manual", governmentFormat: "portal_entry",
    submissionUrl: "https://www.etax.gov.bc.ca/", watermark: "Working copy — file and remit through BC eTaxBC. Not a government return.",
    boxes: [
      { lineCode: "A", label: "Total sales", sign: 1, sequence: 10 },
      { lineCode: "B", label: "Taxable sales and leases", sign: 1, sequence: 20, basis: "taxable_base", glMap: "sales" },
      { lineCode: "C", label: "PST collected (7%)", sign: -1, sequence: 30, basis: "tax_collected", glMap: "sales" },
      { lineCode: "D", label: "Adjustments", sign: 1, sequence: 40 },
      { lineCode: "E", label: "Net PST due", sign: 1, sequence: 50, formula: "C + D" },
    ],
  },
  {
    code: "CA_SK_PST", name: "Saskatchewan PST Return", country: "CA",
    jurisdiction: { code: "CA-SK", name: "Saskatchewan", country: "CA", region: "SK", level: "state", taxType: "pst" },
    defaultFrequency: "monthly", submissionChannel: "portal_manual", governmentFormat: "portal_entry",
    submissionUrl: "https://sets.saskatchewan.ca/", watermark: "Working copy — file and remit through Saskatchewan SETS. Not a government return.",
    boxes: [
      { lineCode: "1", label: "Total sales", sign: 1, sequence: 10 },
      { lineCode: "2", label: "Taxable sales", sign: 1, sequence: 20, basis: "taxable_base", glMap: "sales" },
      { lineCode: "3", label: "Tax collected (6%)", sign: -1, sequence: 30, basis: "tax_collected", glMap: "sales" },
      { lineCode: "4", label: "Adjustments", sign: 1, sequence: 40 },
      { lineCode: "5", label: "Net tax due", sign: 1, sequence: 50, formula: "3 + 4" },
    ],
  },
  {
    code: "CA_MB_RST", name: "Manitoba Retail Sales Tax Return", country: "CA",
    jurisdiction: { code: "CA-MB", name: "Manitoba", country: "CA", region: "MB", level: "state", taxType: "pst" },
    defaultFrequency: "monthly", submissionChannel: "portal_manual", governmentFormat: "portal_entry",
    submissionUrl: "https://taxcess.gov.mb.ca/", watermark: "Working copy — file and remit through Manitoba TAXcess. Not a government return.",
    boxes: [
      { lineCode: "1", label: "Total sales", sign: 1, sequence: 10 },
      { lineCode: "2", label: "Taxable sales", sign: 1, sequence: 20, basis: "taxable_base", glMap: "sales" },
      { lineCode: "3", label: "RST collected (7%)", sign: -1, sequence: 30, basis: "tax_collected", glMap: "sales" },
      { lineCode: "4", label: "Commission / adjustments", sign: 1, sequence: 40 },
      { lineCode: "5", label: "Net RST due", sign: 1, sequence: 50, formula: "3 + 4" },
    ],
  },
  {
    code: "CA_QC_QST", name: "Québec QST Return", country: "CA",
    jurisdiction: { code: "CA-QC", name: "Québec", country: "CA", region: "QC", level: "state", taxType: "qst" },
    defaultFrequency: "quarterly", submissionChannel: "portal_manual", governmentFormat: "portal_entry",
    submissionUrl: "https://www.revenuquebec.ca/en/",
    watermark: "Working copy — file and remit through Revenu Québec. Not a government return.",
    boxes: [
      { lineCode: "205", label: "Taxable sales (QST-eligible)", sign: 1, sequence: 10, basis: "taxable_base", glMap: "sales" },
      { lineCode: "203", label: "QST collected (9.975%)", sign: -1, sequence: 20, basis: "tax_collected", glMap: "sales" },
      { lineCode: "205I", label: "Input tax refunds (ITRs)", sign: 1, sequence: 30, basis: "tax_paid", glMap: "purchases" },
      { lineCode: "206", label: "Adjustments", sign: 1, sequence: 40 },
      { lineCode: "208", label: "Net QST to remit or refund", sign: 1, sequence: 50, formula: "203 - 205I + 206" },
    ],
  },
];
