import type { TaxReturnPack } from "./types.ts";

export const UNITED_STATES_RETURN_PACKS: readonly TaxReturnPack[] = [
  {
    code: "US_SALES_TAX_WORKPAPER", name: "United States Sales Tax Workpaper", country: "US",
    jurisdiction: { code: "US", name: "United States", country: "US", level: "country", taxType: "sales_use" },
    defaultFrequency: "monthly", submissionChannel: "portal_manual", governmentFormat: "portal_entry",
    submissionUrl: "https://www.usa.gov/state-taxes",
    watermark: "Not a government return — customize for each state and local jurisdiction before filing",
    boxes: [
      { lineCode: "GROSS_SALES", label: "Gross sales", sign: 1, sequence: 10 },
      { lineCode: "EXEMPT_SALES", label: "Exempt and non-taxable sales", sign: 1, sequence: 20 },
      { lineCode: "TAXABLE_SALES", label: "Taxable sales", sign: 1, sequence: 30, basis: "taxable_base", glMap: "sales" },
      { lineCode: "TAX_COLLECTED", label: "Sales and use tax collected", sign: -1, sequence: 40, basis: "tax_collected", glMap: "sales" },
      { lineCode: "ADJUSTMENTS", label: "Jurisdiction adjustments", sign: 1, sequence: 50 },
      { lineCode: "TAX_DUE", label: "Tax due before jurisdiction-specific credits and fees", sign: 1, sequence: 60, formula: "TAX_COLLECTED + ADJUSTMENTS" },
    ],
  },
  {
    code: "US_CA_CDTFA401", name: "California Sales and Use Tax Return (CDTFA-401)", country: "US",
    jurisdiction: { code: "US-CA", name: "California", country: "US", region: "CA", level: "state", taxType: "sales_use" },
    defaultFrequency: "quarterly", submissionChannel: "portal_manual", governmentFormat: "portal_entry",
    submissionUrl: "https://onlineservices.cdtfa.ca.gov",
    watermark: "Working copy — file through CDTFA online services; district/local rates configured per jurisdiction",
    boxes: [
      { lineCode: "1", label: "Total sales", sign: 1, sequence: 10 },
      { lineCode: "2", label: "Purchases subject to use tax", sign: 1, sequence: 20 },
      { lineCode: "3", label: "Total", sign: 1, sequence: 30, formula: "1 + 2" },
      { lineCode: "11", label: "Total nontaxable transactions", sign: 1, sequence: 40 },
      { lineCode: "12", label: "Transactions subject to tax", sign: 1, sequence: 50, formula: "3 - 11" },
      { lineCode: "19", label: "Total tax amount (state, county, local, district)", sign: -1, sequence: 60, basis: "tax_collected", glMap: "sales" },
      { lineCode: "20", label: "Credits", sign: 1, sequence: 70 },
      { lineCode: "21", label: "Net tax", sign: 1, sequence: 80, formula: "19 - 20" },
    ],
  },
  {
    code: "US_TX_01114", name: "Texas Sales and Use Tax Return (01-114)", country: "US",
    jurisdiction: { code: "US-TX", name: "Texas", country: "US", region: "TX", level: "state", taxType: "sales_use" },
    defaultFrequency: "monthly", submissionChannel: "portal_manual", governmentFormat: "portal_entry",
    submissionUrl: "https://comptroller.texas.gov/taxes/file-pay/",
    watermark: "Working copy — file through Texas Comptroller Webfile; local rates configured per jurisdiction",
    boxes: [
      { lineCode: "1", label: "Total sales", sign: 1, sequence: 10 },
      { lineCode: "2", label: "Taxable sales", sign: 1, sequence: 20, basis: "taxable_base", glMap: "sales" },
      { lineCode: "3", label: "Taxable purchases", sign: 1, sequence: 30 },
      { lineCode: "4", label: "Amount subject to state tax", sign: 1, sequence: 40, formula: "2 + 3" },
      { lineCode: "7", label: "Tax due (state and local)", sign: -1, sequence: 50, basis: "tax_collected", glMap: "sales" },
      { lineCode: "13", label: "Net tax due", sign: 1, sequence: 60, formula: "7" },
    ],
  },
  {
    code: "US_NY_ST100", name: "New York State and Local Sales and Use Tax Return (ST-100)", country: "US",
    jurisdiction: { code: "US-NY", name: "New York", country: "US", region: "NY", level: "state", taxType: "sales_use" },
    defaultFrequency: "quarterly", submissionChannel: "portal_manual", governmentFormat: "portal_entry",
    submissionUrl: "https://www.tax.ny.gov/online/",
    watermark: "Working copy — file through NY Online Services; jurisdiction rates configured per locality",
    boxes: [
      { lineCode: "1", label: "Gross sales and services", sign: 1, sequence: 10 },
      { lineCode: "1a", label: "Nontaxable sales", sign: 1, sequence: 20 },
      { lineCode: "12", label: "Total taxable sales and services", sign: 1, sequence: 30, basis: "taxable_base", glMap: "sales" },
      { lineCode: "14", label: "Total sales and use tax", sign: -1, sequence: 40, basis: "tax_collected", glMap: "sales" },
      { lineCode: "17", label: "Taxes due", sign: 1, sequence: 50, formula: "14" },
    ],
  },
  {
    code: "US_FL_DR15", name: "Florida Sales and Use Tax Return (DR-15)", country: "US",
    jurisdiction: { code: "US-FL", name: "Florida", country: "US", region: "FL", level: "state", taxType: "sales_use" },
    defaultFrequency: "monthly", submissionChannel: "portal_manual", governmentFormat: "portal_entry",
    submissionUrl: "https://floridarevenue.com/taxes/eservices/",
    watermark: "Working copy — file through Florida DOR e-Services; discretionary surtax configured per county",
    boxes: [
      { lineCode: "A1", label: "Gross sales", sign: 1, sequence: 10 },
      { lineCode: "A2", label: "Exempt sales", sign: 1, sequence: 20 },
      { lineCode: "A3", label: "Taxable amount", sign: 1, sequence: 30, basis: "taxable_base", glMap: "sales" },
      { lineCode: "5", label: "Total amount of tax due", sign: -1, sequence: 40, basis: "tax_collected", glMap: "sales" },
      { lineCode: "6", label: "Less lawful deductions", sign: 1, sequence: 50 },
      { lineCode: "7", label: "Net tax due", sign: 1, sequence: 60, formula: "5 - 6" },
    ],
  },
  {
    code: "US_990", name: "Form 990 annual workpaper", country: "US",
    jurisdiction: { code: "US", name: "United States", country: "US", level: "federal", taxType: "other" },
    defaultFrequency: "annual", submissionChannel: "portal_manual", governmentFormat: "paper",
    submissionUrl: "https://www.irs.gov/charities-non-profits/form-990-resources-and-tools",
    watermark: "WORKPAPER — not a filed return; review every line before filing",
    boxes: [
      { lineCode: "VIII12A", label: "Part VIII, line 12: total revenue", sign: 1, sequence: 10, inputKey: "form990.revenue.total" },
      { lineCode: "IX25B", label: "Part IX, line 25, column B: program services", sign: 1, sequence: 20, inputKey: "form990.expense.program" },
      { lineCode: "IX25C", label: "Part IX, line 25, column C: management and general", sign: 1, sequence: 21, inputKey: "form990.expense.management_general" },
      { lineCode: "IX25D", label: "Part IX, line 25, column D: fundraising", sign: 1, sequence: 22, inputKey: "form990.expense.fundraising" },
      { lineCode: "IX25A", label: "Part IX, line 25, column A: total functional expenses", sign: 1, sequence: 23, formula: "IX25B + IX25C + IX25D" },
      { lineCode: "X16A", label: "Part X, line 16, beginning of year: total assets", sign: 1, sequence: 30, inputKey: "form990.position.assets.opening" },
      { lineCode: "X16B", label: "Part X, line 16, end of year: total assets", sign: 1, sequence: 31, inputKey: "form990.position.assets.ending" },
      { lineCode: "X26A", label: "Part X, line 26, beginning of year: total liabilities", sign: 1, sequence: 32, inputKey: "form990.position.liabilities.opening" },
      { lineCode: "X26B", label: "Part X, line 26, end of year: total liabilities", sign: 1, sequence: 33, inputKey: "form990.position.liabilities.ending" },
      { lineCode: "X32A", label: "Part X, line 32, beginning of year: total net assets", sign: 1, sequence: 34, inputKey: "form990.position.net_assets.opening" },
      { lineCode: "X32B", label: "Part X, line 32, end of year: total net assets", sign: 1, sequence: 35, inputKey: "form990.position.net_assets.ending" },
      { lineCode: "X33A", label: "Part X, line 33, beginning of year: total liabilities and net assets", sign: 1, sequence: 36, formula: "X26A + X32A" },
      { lineCode: "X33B", label: "Part X, line 33, end of year: total liabilities and net assets", sign: 1, sequence: 37, formula: "X26B + X32B" },
      { lineCode: "I12", label: "Part I, line 12: total revenue", sign: 1, sequence: 40, formula: "VIII12A" },
      { lineCode: "I18", label: "Part I, line 18: total expenses", sign: 1, sequence: 41, formula: "IX25A" },
      { lineCode: "I19", label: "Part I, line 19: revenue less expenses", sign: 1, sequence: 42, formula: "I12 - I18" },
      { lineCode: "I20", label: "Part I, line 20: total assets", sign: 1, sequence: 43, formula: "X16B" },
      { lineCode: "I21", label: "Part I, line 21: total liabilities", sign: 1, sequence: 44, formula: "X26B" },
      { lineCode: "I22", label: "Part I, line 22: net assets", sign: 1, sequence: 45, formula: "X32B" },
    ],
  },
];
