import type { ReportCustomQuery, ReportMeasure } from './types'

const count = (label: string, status?: string, field = 'status'): ReportMeasure => ({ fn: 'count', label, ...(status ? { filter: { combinator: 'and' as const, rules: [{ field, op: 'eq' as const, value: status }] } } : {}) })
const summary = (entity: string, measures: ReportMeasure[]): ReportCustomQuery => ({ entity, periodField: null, mode: 'summarize', columns: [], breakouts: [], measures, filters: null, groupBy: null, limit: 1000 })

/** Current-state portfolio and control reports belong to the native Reports catalog. */
export const PORTFOLIO_SUMMARY_REPORTS = [
  { slug: 'analytics-allocation-controls', name: 'Allocation controls', description: 'Current allocation run controls: posted runs, pending approvals, failed calculations and total runs.', query: summary('allocation_runs', [count('Posted runs', 'posted'), count('Awaiting approval', 'pending_approval'), count('Failed runs', 'failed'), count('Allocation runs')]) },
  { slug: 'analytics-payroll-reconciliation', name: 'Payroll reconciliation', description: 'Filed payroll comparison results: differences, exact matches, tolerated differences and unattributed amounts. Counts refer to comparison cells.', query: summary('payroll_parallel_findings', [count('Differences', 'difference', 'classification'), count('Exact matches', 'match', 'classification'), count('Within tolerance', 'within_tolerance', 'classification'), count('Unattributed cells', 'unattributed', 'classification')]) },
  { slug: 'analytics-workforce-capacity', name: 'Workforce capacity', description: 'Current workforce establishment: planned, funded, filled and vacant full-time equivalents.', query: summary('hrm_positions', [ { fn: 'sum', column: 'planned_fte', label: 'Planned FTE' }, { fn: 'sum', column: 'funded_fte', label: 'Funded FTE' }, { fn: 'sum', column: 'filled_fte', label: 'Filled FTE' }, { fn: 'sum', column: 'vacant_fte', label: 'Vacant FTE' } ]) },
  { slug: 'analytics-project-portfolio', name: 'Project portfolio', description: 'Current project lifecycle: active work, quotations, awards and closed projects.', query: summary('projects', [count('Active projects', 'active'), count('Quoted projects', 'quoted'), count('Awarded projects', 'awarded'), count('Closed projects', 'closed')]) },
  { slug: 'analytics-asset-lifecycle', name: 'Asset lifecycle', description: 'Current fixed-asset register: assets in service, fully depreciated, disposed and awaiting activation.', query: summary('fixed_assets', [count('In service', 'in_service'), count('Fully depreciated', 'fully_depreciated'), count('Disposed', 'disposed'), count('Draft assets', 'draft')]) },
  { slug: 'analytics-production', name: 'Production overview', description: 'Current production orders: released, in progress, on hold and completed.', query: summary('manufacturing_work_orders', [count('Released orders', 'released'), count('In progress', 'in_progress'), count('On hold', 'on_hold'), count('Completed orders', 'done')]) },
  { slug: 'analytics-property-portfolio', name: 'Property portfolio', description: 'Current managed-property portfolio: active, inactive, sold and total properties.', query: summary('managed_property_portfolio', [count('Active properties', 'active'), count('Inactive properties', 'inactive'), count('Sold properties', 'sold'), count('Properties')]) },
  { slug: 'analytics-grant-portfolio', name: 'Grant portfolio', description: 'Current grant lifecycle: awarded, active, closed out and draft grants. Requires nonprofit reporting permission.', query: summary('grant_pipeline', [count('Awarded grants', 'awarded'), count('Active grants', 'active'), count('Closed out grants', 'closed_out'), count('Draft grants', 'draft')]) },
]
