import type { ReportEntity } from "./entities";
const shared = {
  category: "crm" as const,
  featureKey: "salesManagement",
  requiredPermission: "crm.forecasts.read",
  currencyColumn: "currency",
};
export const SALES_REPORT_ENTITIES: ReportEntity[] = [
  {
    ...shared,
    key: "sales_evidence",
    label: "Sales evidence",
    description:
      "Immutable attributed sales credits and reversals, including historical attribution gaps.",
    from: "crm_sales_evidence e left join parties p on p.org_id=e.org_id and p.id=e.employee_id left join crm_sales_teams t on t.org_id=e.org_id and t.id=e.sales_team_id",
    orgColumn: "e.org_id",
    subsidiaryScope: { column: "e.subsidiary_id" },
    timeKey: "effective_date",
    columns: [
      { key: "id", label: "Evidence key", kind: "uuid", expr: "e.id" },
      {
        key: "source_id",
        label: "Source record",
        kind: "uuid",
        expr: "e.source_id",
      },
      {
        key: "source_kind",
        label: "Source kind",
        kind: "enum",
        expr: "e.source_kind",
        options: ["opportunity", "document"],
      },
      {
        key: "source_number",
        label: "Source number",
        kind: "text",
        expr: "e.source_number",
      },
      {
        key: "employee",
        label: "Employee",
        kind: "text",
        expr: "coalesce(p.display_name,'Unattributed')",
      },
      {
        key: "employee_id",
        label: "Employee key",
        kind: "uuid",
        expr: "e.employee_id",
      },
      { key: "team", label: "Team", kind: "text", expr: "t.name" },
      {
        key: "effective_date",
        label: "Effective date",
        kind: "date",
        expr: "e.effective_date",
      },
      {
        key: "metric",
        label: "Measure",
        kind: "enum",
        expr: "e.metric",
        options: ["closed_won", "net_invoiced"],
      },
      {
        key: "event_kind",
        label: "Event",
        kind: "enum",
        expr: "e.event_kind",
        options: ["credit", "reversal"],
      },
      { key: "currency", label: "Currency", kind: "text", expr: "e.currency" },
      {
        key: "amount",
        label: "Amount",
        kind: "money",
        expr: "e.amount",
        txnCurrency: true,
      },
    ],
  },
  {
    ...shared,
    key: "sales_quota_attainment",
    label: "Sales quota attainment",
    description:
      "Quota version, lifecycle, employee or team target, and actuals from immutable sales evidence in the target currency.",
    from: `crm_sales_quotas q left join parties p on p.org_id=q.org_id and p.id=q.employee_id left join crm_sales_teams t on t.org_id=q.org_id and t.id=q.sales_team_id left join lateral (select sum(e.amount) as actual from crm_sales_evidence e where e.org_id=q.org_id and e.subsidiary_id is not distinct from q.subsidiary_id and e.currency=q.currency and e.metric=q.metric and e.effective_date between q.period_start and q.period_end and ((q.employee_id is not null and e.employee_id=q.employee_id) or (q.sales_team_id is not null and e.sales_team_id=q.sales_team_id))) a on true`,
    orgColumn: "q.org_id",
    subsidiaryScope: { column: "q.subsidiary_id" },
    timeKey: "period_start",
    columns: [
      { key: "id", label: "Quota key", kind: "uuid", expr: "q.id" },
      { key: "name", label: "Quota", kind: "text", expr: "q.name" },
      {
        key: "target",
        label: "Target",
        kind: "text",
        expr: "coalesce(p.display_name,t.name)",
      },
      {
        key: "employee_id",
        label: "Employee key",
        kind: "uuid",
        expr: "q.employee_id",
      },
      {
        key: "sales_team_id",
        label: "Team key",
        kind: "uuid",
        expr: "q.sales_team_id",
      },
      {
        key: "parent_quota_id",
        label: "Parent quota",
        kind: "uuid",
        expr: "q.parent_quota_id",
      },
      {
        key: "supersedes_id",
        label: "Replaces quota",
        kind: "uuid",
        expr: "q.supersedes_id",
      },
      {
        key: "period_start",
        label: "Period start",
        kind: "date",
        expr: "q.period_start",
      },
      {
        key: "period_end",
        label: "Period end",
        kind: "date",
        expr: "q.period_end",
      },
      {
        key: "lifecycle",
        label: "Lifecycle",
        kind: "enum",
        expr: "q.lifecycle",
        options: [
          "draft",
          "pending_approval",
          "approved",
          "superseded",
          "closed",
        ],
      },
      {
        key: "metric",
        label: "Measure",
        kind: "enum",
        expr: "q.metric",
        options: ["closed_won", "net_invoiced"],
      },
      { key: "currency", label: "Currency", kind: "text", expr: "q.currency" },
      {
        key: "amount",
        label: "Target amount",
        kind: "money",
        expr: "q.amount",
        txnCurrency: true,
      },
      {
        key: "actual",
        label: "Actual",
        kind: "money",
        expr: "coalesce(a.actual,0)",
        txnCurrency: true,
      },
      {
        key: "attainment",
        label: "Attainment percent",
        kind: "number",
        expr: "case when q.amount=0 then null else coalesce(a.actual,0)*100/q.amount end",
      },
    ],
  },
];
