// GENERATED by scripts/payroll-new-tax-year.ts from the rates-<year>.ts modules
// present in this directory. Do not edit by hand — add a year by running the
// scaffold, then transcribe the published T4127 figures into the year module.
import type { EditionRates } from "./rates.ts";

export const CA_EXTRA_EDITIONS: readonly EditionRates[] = [];
