import type { PayrollPeriodOpeningTreatment } from '../period-opening-declaration.ts';

/** The same exact factor vocabulary consumed by Canada's native period-share calculation. */
export const CA_PERIOD_OPENING_TREATMENT: PayrollPeriodOpeningTreatment = {
  fields: [
    { key: 'pensionable', label: 'CPP/QPP pensionable earnings', basis: 'pensionable', payable: false },
    { key: 'insurable', label: 'EI insurable earnings', basis: 'insurable', payable: false },
    { key: 'periodicIncome', label: 'Periodic taxable income (I)', factorKey: 'I', payable: false },
    { key: 'nonPeriodicIncome', label: 'Non-periodic taxable income (B)', factorKey: 'B', payable: false },
    { key: 'pensionDeductions', label: 'Periodic pension deductions (F)', factorKey: 'F', payable: true },
    { key: 'bonusPensionDeductions', label: 'Pension deductions from non-periodic pay (F3)', factorKey: 'F3', payable: true },
    { key: 'alimonyDeductions', label: 'Alimony deducted at source (F2)', factorKey: 'F2', payable: true },
    { key: 'unionDues', label: 'Periodic union dues (U1)', factorKey: 'U1', payable: true },
    { key: 'cpp', label: 'Employee CPP/QPP already withheld (C)', factorKey: 'C', withheldSystemKey: 'cpp', payable: true },
    { key: 'cpp2', label: 'Employee CPP2 already withheld (C2)', factorKey: 'C2', withheldSystemKey: 'cpp2', payable: true },
    { key: 'ei', label: 'Employee EI already withheld', factorKey: 'EI', withheldSystemKey: 'ei', payable: true },
    { key: 'enhancedCppPeriodic', label: 'Enhanced CPP deduction on periodic pay (F5A)', factorKey: 'F5A', payable: true },
    { key: 'enhancedCppBonus', label: 'Enhanced CPP deduction on non-periodic pay (F5B)', factorKey: 'F5B', payable: true },
    { key: 'incomeTax', label: 'Federal and combined provincial income tax already withheld', withheldSystemKey: 'income_tax', payable: true },
    { key: 'quebecTax', label: 'Québec income tax already withheld', withheldSystemKey: 'qc_income_tax', payable: true },
    { key: 'qpipPeriodicEarnings', label: 'Periodic QPIP insurable earnings', factorKey: 'CA_QPIP_PE', payable: false },
    { key: 'qpipBonusEarnings', label: 'Non-periodic QPIP insurable earnings', factorKey: 'CA_BQPIP', payable: false },
    { key: 'qpip', label: 'Employee QPIP already withheld', factorKey: 'QPIP', withheldSystemKey: 'qpip', payable: true },
    { key: 'qpipEmployer', label: 'Employer QPIP already paid', factorKey: 'QPIP_ER', payable: true },
    { key: 'quebecBonusAdditionalQpp', label: 'Québec additional QPP attributed to non-periodic pay (CSB)', factorKey: 'QC_CSB', payable: true },
  ],
  annualBounds: [
    { annualOpeningKey: 'pensionableYtd', fieldKeys: ['pensionable'], label: 'Pensionable earnings' },
    { annualOpeningKey: 'insurableYtd', fieldKeys: ['insurable'], label: 'Insurable earnings' },
    { annualOpeningKey: 'taxableYtd', fieldKeys: ['periodicIncome', 'nonPeriodicIncome'], label: 'Taxable income' },
    { annualOpeningKey: 'nonPeriodicYtd', fieldKeys: ['nonPeriodicIncome'], label: 'Non-periodic income' },
    { annualOpeningKey: 'nonPeriodicPensionDeductionsYtd', fieldKeys: ['bonusPensionDeductions'], label: 'Pension deductions from non-periodic pay' },
    { annualOpeningKey: 'unionDuesYtd', fieldKeys: ['unionDues'], label: 'Union dues' },
    { annualOpeningKey: 'cppYtd', fieldKeys: ['cpp'], label: 'CPP/QPP contributions' },
    { annualOpeningKey: 'cpp2Ytd', fieldKeys: ['cpp2'], label: 'CPP2 contributions' },
    { annualOpeningKey: 'eiYtd', fieldKeys: ['ei'], label: 'EI premiums' },
    { annualOpeningKey: 'cpp2BonusYtd', fieldKeys: ['enhancedCppBonus'], label: 'Enhanced CPP attributed to non-periodic pay' },
    { annualOpeningKey: 'taxYtd', fieldKeys: ['incomeTax'], label: 'Federal and combined provincial income tax' },
    { annualOpeningKey: 'qcTaxYtd', fieldKeys: ['quebecTax'], label: 'Québec income tax' },
    { annualOpeningKey: 'program:qpip', fieldKeys: ['qpipPeriodicEarnings', 'qpipBonusEarnings'], label: 'QPIP insurable earnings' },
    { annualOpeningKey: 'qpipYtd', fieldKeys: ['qpip'], label: 'Employee QPIP premiums' },
    { annualOpeningKey: 'qpipEmployerYtd', fieldKeys: ['qpipEmployer'], label: 'Employer QPIP premiums' },
    { annualOpeningKey: 'qcCsbYtd', fieldKeys: ['quebecBonusAdditionalQpp'], label: 'Québec additional QPP on non-periodic pay' },
  ],
  amountBounds: [
    { fieldKeys: ['enhancedCppPeriodic', 'enhancedCppBonus'], withinFieldKeys: ['cpp', 'cpp2'], label: 'Enhanced CPP deductions' },
    { fieldKeys: ['bonusPensionDeductions'], withinFieldKeys: ['nonPeriodicIncome'], label: 'Pension deductions from non-periodic pay' },
    { fieldKeys: ['pensionDeductions', 'alimonyDeductions', 'unionDues'], withinFieldKeys: ['periodicIncome'], label: 'Periodic pre-tax deductions' },
  ],
};
