"use client";
import { useEffect, useId, useRef, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useTranslations, useLocale } from 'next-intl';
import { Button, Input, Label, Select, Textarea, Badge } from '@openbooks/ui';
import { AsyncUrlDrawer } from '@/components/async-url-drawer';
import { InventoryTrackingFields } from '@/components/inventory-tracking-fields';
import { readApiErrorMessage } from '@/lib/api-error';
import { confirmDialog } from '@/lib/confirm';
import { formatDecimal } from '@/lib/money-format';
import type { readManufacturingInspection } from '@openbooks/engine/src/manufacturing/quality-workspace.ts';
type Detail=Awaited<ReturnType<typeof readManufacturingInspection>>;

export function InspectionHost({recordId,closeHref,canInspect,canPost,scrapReasons}:{recordId?:string;closeHref:string;canInspect:boolean;canPost:boolean;scrapReasons:Array<{value:string;label:string}>}) {
  const t=useTranslations('manufacturing.quality'),common=useTranslations('manufacturing'),locale=useLocale(),router=useRouter(),controlId=useId();
  const [data,setData]=useState<Detail|null>(null),[loaded,setLoaded]=useState<string|null>(null),[pending,setPending]=useState(false),[loadError,setLoadError]=useState<string|null>(null),[attempt,setAttempt]=useState(0),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false);
  const [outcome,setOutcome]=useState<'pass'|'fail'>('pass'),[measurements,setMeasurements]=useState<Record<string,string>>({}),[quantity,setQuantity]=useState(''),[lotId,setLotId]=useState(''),[serialId,setSerialId]=useState(''),[reason,setReason]=useState(''),[disposition,setDisposition]=useState<'use_as_is'|'scrap'|'rework'>('use_as_is'),[scrapReasonId,setScrapReasonId]=useState(''),[reworkOperation,setReworkOperation]=useState('');
  const lock=useRef(false),request=useRef<{body:string;key:string}|null>(null);
  const currentIdentity=useRef(recordId);currentIdentity.current=recordId;
  useEffect(()=>()=>{currentIdentity.current=undefined;},[]);
  useEffect(()=>{if(!recordId)return;const controller=new AbortController();setPending(true);setLoadError(null);setError(null);setDirty(false);request.current=null;
    fetch('/api/manufacturing/inspections/'+recordId,{signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error(await readApiErrorMessage(response,t('failed')));return response.json() as Promise<Detail>}).then(value=>{if(controller.signal.aborted)return;setData(value);setLoaded(recordId);setMeasurements(value.measurements);setQuantity(value.disposition==='scrap'?value.remainingInspectionQuantity??'':value.quantity);setLotId(value.lotId??'');setSerialId(value.serialId??'');setReason('');setDisposition('use_as_is');setOutcome('pass');setReworkOperation(value.reworkOperations[0]?.value??'');}).catch(cause=>{if(!controller.signal.aborted)setLoadError(cause instanceof Error?cause.message:t('failed'));}).finally(()=>{if(!controller.signal.aborted)setPending(false);});return()=>controller.abort();
  },[recordId,attempt,t]);
  function changed(){setDirty(true);setError(null);request.current=null;}
  async function save(command:'inspect'|'dispose'|'followup') {
    if(!data||data.id!==recordId||lock.current)return;lock.current=true;setBusy(true);setError(null);
    const identity=data.id;
    try {
      const fields=command==='inspect'?{command,outcome,measurements:Object.fromEntries(Object.entries(measurements).filter(([,value])=>value!=='')),reason:reason.trim()||t('recordedNote'),...(data.operationId?{quantity,lotId:lotId||null,serialId:serialId||null}:{})}:command==='dispose'?{command,action:disposition,reason,...(disposition==='scrap'&&data.operationId?{scrapReasonId}:{}),...(disposition==='rework'&&data.receiptMovementId?{reworkRoutingId:data.reworkOperations.find(operation=>operation.value===reworkOperation)?.routingId,reworkSequence:data.reworkOperations.find(operation=>operation.value===reworkOperation)?.sequence}:{})}:{workOrderId:data.workOrderId,operationId:data.operationId,quantity};
      const body=JSON.stringify(fields);
      if(request.current?.body!==body)request.current={body,key:crypto.randomUUID()};
      const response=await fetch(command==='followup'?'/api/manufacturing/inspections/operation':'/api/manufacturing/inspections/'+identity,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...fields,...(command==='dispose'?{requestKey:request.current.key}:command==='followup'?{id:request.current.key}:{})})});
      if(!response.ok)throw new Error(await readApiErrorMessage(response,t('failed')));
      const value=await response.json();if(currentIdentity.current!==identity){router.refresh();return;}setDirty(false);request.current=null;
      if(command==='followup'){const url=new URL(closeHref,window.location.origin);url.searchParams.set('inspection',value.id);router.push(url.pathname+url.search);}
      else setAttempt(value=>value+1);
      router.refresh();
    }catch(cause){if(currentIdentity.current===identity)setError(cause instanceof Error?cause.message:t('failed'));}finally{lock.current=false;setBusy(false);}
  }
  if(!recordId)return null;
  const visible=loaded===recordId?data:null;
  return <AsyncUrlDrawer open openKey={recordId} closeHref={closeHref} title={visible?.planSnapshot.name??t('title')} size="lg" pending={(pending||!visible)&&!loadError} error={loadError} onRetry={()=>setAttempt(value=>value+1)} beforeClose={()=>!dirty||confirmDialog(common('discardDraft'))}>{visible?<div className="space-y-5">
    <div className="space-y-2"><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-semibold">{visible.itemName}</h2><Badge>{t('status.'+visible.status)}</Badge>{visible.disposition?<Badge>{t('dispositions.'+visible.disposition)}</Badge>:null}</div><p className="text-sm text-slate-500">{formatDecimal(locale,visible.quantity,{maximumFractionDigits:4})} · {[visible.lotNumber,visible.serialNumber].filter(Boolean).join(' · ')||(visible.tracking==='none'?t('untracked'):t('trackingNeeded'))}</p>{visible.workOrderId?<Link className="text-sm text-teal-700 hover:underline" href={('/manufacturing/work-orders?record='+visible.workOrderId) as never}>{visible.workOrderNumber} · {visible.operationName}</Link>:null}</div>
    {!visible.sourceActive?<p className="rounded-lg border p-3 text-sm text-slate-600">{t(visible.receiptMovementId?'sourceReversed':'sourceStopped')}</p>:null}
    {visible.status==='pending'&&canInspect&&visible.sourceActive?<form onSubmit={event=>{event.preventDefault();void save('inspect')}} className="space-y-4">
      {visible.operationId?<div className="grid gap-3 sm:grid-cols-2"><div className="space-y-1"><Label htmlFor={controlId+'quantity'}>{t('quantity')}</Label><Input id={controlId+'quantity'} value={quantity} required disabled={busy} inputMode="decimal" onChange={event=>{changed();setQuantity(event.target.value)}}/></div><div className="sm:col-span-2"><InventoryTrackingFields itemId={visible.itemId} lotId={lotId} serialId={serialId} disabled={busy} canCreate={canInspect} optionsEndpoint={'/api/manufacturing/inspections/'+visible.id+'/tracking'} onChange={(lot,serial)=>{changed();setLotId(lot);setSerialId(serial)}} registerIdentifier={async(kind,number,expiresOn)=>{const response=await fetch('/api/manufacturing/inspections/'+visible.id+'/tracking',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,number,expiresOn})});if(!response.ok)throw new Error(await readApiErrorMessage(response,t('failed')));return response.json();}}/></div></div>:null}
      <div className="space-y-3">{visible.planSnapshot.measures.map(measure=><div key={measure.key} className="grid items-end gap-2 rounded-lg border p-3 sm:grid-cols-2"><div><Label htmlFor={controlId+measure.key}>{measure.label} {measure.required?'*':''}</Label><p className="mt-1 text-xs text-slate-500">{measure.unit} · {measure.minimum??'—'} – {measure.maximum??'—'}</p></div><Input id={controlId+measure.key} value={measurements[measure.key]??''} inputMode="decimal" required={measure.required} disabled={busy} onChange={event=>{changed();setMeasurements(values=>({...values,[measure.key]:event.target.value}))}}/></div>)}</div>
      <div className="space-y-1"><Label htmlFor={controlId+'outcome'}>{t('outcome')}</Label><Select id={controlId+'outcome'} value={outcome} disabled={busy} onChange={event=>{changed();setOutcome(event.target.value as 'pass'|'fail')}}><option value="pass">{t('status.pass')}</option><option value="fail">{t('status.fail')}</option></Select><p className="text-xs text-slate-500">{t('limits')}</p></div><div className="space-y-1"><Label htmlFor={controlId+'reason'}>{t('note')}</Label><Textarea id={controlId+'reason'} minLength={5} maxLength={500} value={reason} disabled={busy} onChange={event=>{changed();setReason(event.target.value)}}/></div><Button type="submit" disabled={busy}>{t('record')}</Button>
    </form>:<div className="space-y-3"><dl className="grid gap-3 sm:grid-cols-2">{visible.planSnapshot.measures.map(measure=><div key={measure.key}><dt className="text-xs text-slate-500">{measure.label}</dt><dd>{visible.measurements[measure.key]??'—'} {measure.unit}</dd></div>)}</dl>{visible.reason?<p className="text-sm">{visible.reason}</p>:null}</div>}
    {visible.status==='fail'&&!visible.disposition&&canInspect&&visible.sourceActive?<form className="space-y-3 rounded-xl border p-4" onSubmit={event=>{event.preventDefault();void save('dispose')}}><div><h3 className="font-semibold">{t('disposition')}</h3><p className="mt-1 text-sm text-slate-500">{t('held')}</p></div><Select aria-label={t('disposition')} value={disposition} disabled={busy} onChange={event=>{changed();setDisposition(event.target.value as typeof disposition)}}>{(['use_as_is','scrap','rework'] as const).filter(action=>action==='use_as_is'||canPost).map(action=><option key={action} value={action}>{t('dispositions.'+action)}</option>)}</Select>{disposition==='rework'&&visible.receiptMovementId?<div className="space-y-2"><Label htmlFor={controlId+'repairOperation'}>{t('repairOperation')}</Label><Select id={controlId+'repairOperation'} required value={reworkOperation} disabled={busy} onChange={event=>{changed();setReworkOperation(event.target.value)}}><option value="">{common('choose')}</option>{visible.reworkOperations.map(operation=><option key={operation.value} value={operation.value}>{operation.label}</option>)}</Select><p className="text-sm text-slate-500">{t(visible.reworkOperations.length?'receiptReworkNote':'repairRoutingMissing')}</p>{!visible.reworkOperations.length?<Button variant="outline" asChild><Link href="/manufacturing/routings">{t('reviewRepairRoutings')}</Link></Button>:null}</div>:null}{disposition==='scrap' &&visible.operationId?<Select aria-label={t('scrapReason')} required value={scrapReasonId} disabled={busy} onChange={event=>{changed();setScrapReasonId(event.target.value)}}><option value="">{common('choose')}</option>{scrapReasons.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</Select>:null}<Label htmlFor={controlId+'dispositionReason'}>{t('note')}</Label><Textarea id={controlId+'dispositionReason'} minLength={5} maxLength={500} required value={reason} disabled={busy} onChange={event=>{changed();setReason(event.target.value)}}/><Button type="submit" disabled={busy||(disposition==='rework'&&!!visible.receiptMovementId&&!reworkOperation)||(disposition==='scrap'&&!!visible.operationId&&!scrapReasonId)}>{t('dispose')}</Button></form>:null}
    {visible.canFollowup&&canInspect&&visible.remainingInspectionQuantity!==null&&visible.remainingInspectionQuantity!=='0.0000'&&(visible.status==='pass'||visible.disposition==='use_as_is'||visible.disposition==='scrap'||visible.reworkResolved)?<div className="space-y-2"><p className="text-sm text-slate-500">{t(visible.disposition==='scrap'?'followupNote':'additionalInspectionNote')}</p><Label htmlFor={controlId+'nextQuantity'}>{t('quantity')}</Label><Input id={controlId+'nextQuantity'} value={quantity} inputMode="decimal" disabled={busy} onChange={event=>{changed();setQuantity(event.target.value)}}/><Button disabled={busy} onClick={()=>void save('followup')}>{t(visible.disposition==='scrap'?'followup':'additionalInspection')}</Button></div>:null}
    {visible.disposition==='rework'&&visible.reworkResolved?<p role="status" className="rounded-lg border p-3 text-sm text-slate-600">{t(visible.reworkLoss?'repairDisposed':'repairAccepted')}</p>:null}
    {visible.dispositionResult?.workOrderId?<Button variant="outline" asChild><Link href={('/manufacturing/work-orders?record='+String(visible.dispositionResult.workOrderId)) as never}>{t('openRework')}</Link></Button>:null}
    {error?<p role="alert" className="text-sm text-red-700">{error}</p>:null}
  </div>:null}</AsyncUrlDrawer>;
}
