import { sql } from "drizzle-orm";
import {
  bigint,
  boolean,
  check,
  date,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { auditColumns, currencyCode, id, money, orgRef } from "./helpers";

export const CRM_FORECAST_CATEGORIES = ["omitted", "worst_case", "most_likely", "upside"] as const;

export const crmOpportunities = pgTable(
  "crm_opportunities",
  {
    id: id(),
    orgId: orgRef(),
    opportunityNumber: text("opportunity_number").notNull(),
    title: text("title").notNull(),
    partyId: uuid("party_id"),
    primaryContactId: uuid("primary_contact_id"),
    ownerUserId: uuid("owner_user_id"),
    salesTeamId: uuid("sales_team_id"),
    statusId: uuid("status_id").notNull(),
    leadSourceId: uuid("lead_source_id"),
    expectedCloseDate: date("expected_close_date"),
    forecastCategory: text("forecast_category", { enum: CRM_FORECAST_CATEGORIES }).notNull().default("upside"),
    probability: integer("probability").notNull().default(0),
    currency: currencyCode("currency").notNull(),
    projectedAmount: money("projected_amount").notNull().default("0"),
    weightedAmount: money("weighted_amount").notNull().default("0"),
    rangeLow: money("range_low"),
    rangeHigh: money("range_high"),
    subsidiaryId: uuid("subsidiary_id"),
    departmentId: uuid("department_id"),
    locationId: uuid("location_id"),
    classId: uuid("class_id"),
    extraDims: jsonb("extra_dims").notNull().default({}),
    nextStep: text("next_step"),
    competitorNotes: text("competitor_notes"),
    winLossReason: text("win_loss_reason"),
    description: text("description"),
    closedAt: timestamp("closed_at", { withTimezone: true }),
    isActive: boolean("is_active").notNull().default(true),
    custom: jsonb("custom").notNull().default({}),
    /** Strictly increasing OCC counter, see documents.revisionSeq (migration 0167). */
    revisionSeq: bigint("revision_seq", { mode: "number" }).notNull().default(0),
    ...auditColumns,
  },
  (t) => [
    uniqueIndex("crm_opportunities_org_number").on(t.orgId, t.opportunityNumber),
    index("crm_opportunities_pipeline").on(t.orgId, t.statusId, t.expectedCloseDate),
    index("crm_opportunities_owner").on(t.orgId, t.ownerUserId, t.expectedCloseDate),
    index("crm_opportunities_party").on(t.orgId, t.partyId),
    check("crm_opportunity_probability", sql`${t.probability} >= 0 and ${t.probability} <= 100`),
    check("crm_opportunity_amounts", sql`${t.projectedAmount} >= 0 and ${t.weightedAmount} >= 0 and (${t.rangeLow} is null or ${t.rangeLow} >= 0) and (${t.rangeHigh} is null or ${t.rangeHigh} >= 0) and (${t.rangeLow} is null or ${t.rangeHigh} is null or ${t.rangeHigh} >= ${t.rangeLow})`),
  ],
);
