// GENERATED by scripts/generate-locale-indexes.mjs — do not edit by hand.
// Every catalog in web/messages/en, keyed by its camel-cased file name, as
// the next-intl messages tree. Adding a namespace: create <ns>.json in every
// locale directory, then rerun the generator.
import accounting from './accounting.json'
import accounts from './accounts.json'
import admin from './admin.json'
import agents from './agents.json'
import allocations from './allocations.json'
import analytics from './analytics.json'
import ap from './ap.json'
import apiDocs from './apiDocs.json'
import apiErrors from './apiErrors.json'
import applications from './applications.json'
import approvals from './approvals.json'
import apps from './apps.json'
import ar from './ar.json'
import assets from './assets.json'
import assistant from './assistant.json'
import banking from './banking.json'
import budgets from './budgets.json'
import close from './close.json'
import common from './common.json'
import compliance from './compliance.json'
import continuousClose from './continuous-close.json'
import contractCosts from './contractCosts.json'
import crm from './crm.json'
import customers from './customers.json'
import customization from './customization.json'
import dashboard from './dashboard.json'
import data from './data.json'
import docs from './docs.json'
import documents from './documents.json'
import entities from './entities.json'
import estimates from './estimates.json'
import expenses from './expenses.json'
import fieldTickets from './fieldTickets.json'
import fulfillment from './fulfillment.json'
import home from './home.json'
import hrm from './hrm.json'
import inbox from './inbox.json'
import insights from './insights.json'
import inventory from './inventory.json'
import items from './items.json'
import journal from './journal.json'
import knowledge from './knowledge.json'
import laborPricing from './labor-pricing.json'
import login from './login.json'
import nav from './nav.json'
import nonprofit from './nonprofit.json'
import parties from './parties.json'
import payments from './payments.json'
import payroll from './payroll.json'
import pdfTemplates from './pdfTemplates.json'
import projectTypes from './projectTypes.json'
import projects from './projects.json'
import purchaseOrders from './purchaseOrders.json'
import purchasing from './purchasing.json'
import query from './query.json'
import receipts from './receipts.json'
import records from './records.json'
import reports from './reports.json'
import resourcing from './resourcing.json'
import returns from './returns.json'
import revenue from './revenue.json'
import salesOrders from './salesOrders.json'
import shell from './shell.json'
import subcontracts from './subcontracts.json'
import sync from './sync.json'
import tax from './tax.json'
import timesheets from './timesheets.json'
import ui from './ui.json'
import warehouse from './warehouse.json'

export default {
  accounting,
  accounts,
  admin,
  agents,
  allocations,
  analytics,
  ap,
  apiDocs,
  apiErrors,
  applications,
  approvals,
  apps,
  ar,
  assets,
  assistant,
  banking,
  budgets,
  close,
  common,
  compliance,
  continuousClose,
  contractCosts,
  crm,
  customers,
  customization,
  dashboard,
  data,
  docs,
  documents,
  entities,
  estimates,
  expenses,
  fieldTickets,
  fulfillment,
  home,
  hrm,
  inbox,
  insights,
  inventory,
  items,
  journal,
  knowledge,
  laborPricing,
  login,
  nav,
  nonprofit,
  parties,
  payments,
  payroll,
  pdfTemplates,
  projectTypes,
  projects,
  purchaseOrders,
  purchasing,
  query,
  receipts,
  records,
  reports,
  resourcing,
  returns,
  revenue,
  salesOrders,
  shell,
  subcontracts,
  sync,
  tax,
  timesheets,
  ui,
  warehouse,
} as const
