/** Quote-to-cash: the web routes' contract for ramp-priced quotes, e-signature, and activation. */
export {
  activateQuote,
  clearQuoteToCashSettings,
  deleteQuoteTerm,
  declineQuoteSignature,
  getQuoteToCashSettings,
  latestSignatureRequest,
  QUOTE_SUBJECT_TABLE,
  quoteCashPreview,
  QuoteToCashError,
  publicQuoteSignView,
  requestQuoteSignature,
  saveQuoteTerm,
  saveQuoteToCashSettings,
  signQuoteSignature,
  viewQuoteSignature,
  voidSignatureRequestsForSubject,
} from "./quote-to-cash.ts";
export type {
  ActivateQuoteOptions,
  ActivateQuoteResult,
  PublicQuoteSignTerm,
  PublicQuoteSignView,
  QuoteCashPreview,
  QuoteToCashSettings,
  SaveQuoteToCashSettingsInput,
  QuoteRow,
  RampPeriod,
  RampSchedule,
  RequestSignatureInput,
  RequestSignatureResult,
  SaveQuoteTermInput,
  SaveQuoteTermResult,
  SignatureRequestRow,
  SignatureView,
  SignQuoteInput,
  SignQuoteResult,
} from "./quote-to-cash.ts";
