/** Setup-registry billing entities (split from registry.ts; pure moves only). */
import type { SetupEntity } from '../types'

export const BILLING_ENTITIES: SetupEntity[] = [
  // --- Billing & numbering -------------------------------------------------
  {
    key: 'payment-terms',
    table: 'payment_terms',
    groupKey: 'billing',
    iconKey: 'calendar',
    orgScoped: true,
    orderBy: 'name',
    hasActive: true,
    columns: [
      { key: 'name', kind: 'text' },
      { key: 'netDays', kind: 'number' },
      { key: 'discountDays', kind: 'number' },
      { key: 'discountPercent', kind: 'percent' },
      { key: 'isActive', kind: 'badge-active' },
    ],
    fields: [
      { key: 'name', kind: 'text', required: true },
      { key: 'netDays', kind: 'integer', required: true },
      { key: 'discountDays', kind: 'integer' },
      { key: 'discountPercent', kind: 'percent' },
      { key: 'isActive', kind: 'boolean' },
    ],
  },
  {
    // Corporate cards as first-class instruments (0171): each card names its
    // holder and the single liability account it posts to, so expense reports
    // can fund company-paid and personal lines through the header
    // payment_card_id instead of hand-routing overrides per report. One row
    // per physical card — including one row per employee when (as observed at
    // a production tenant) the chart carries a liability account per cardholder. The network and
    // last-four are free-text card detail, never an allow-list: no brand or
    // product gets built-in treatment.
    key: 'payment-cards',
    table: 'payment_cards',
    groupKey: 'accounting',
    iconKey: 'payments',
    orgScoped: true,
    actorCols: true,
    orderBy: 'label',
    hasActive: true,
    columns: [
      { key: 'label', kind: 'text' },
      { key: 'holderPartyId', kind: 'ref', ref: 'employees' },
      { key: 'liabilityAccountId', kind: 'ref', ref: 'accounts' },
      { key: 'isActive', kind: 'badge-active' },
    ],
    fields: [
      { key: 'label', kind: 'text', required: true },
      { key: 'holderPartyId', kind: 'ref', ref: 'employees', required: true },
      { key: 'liabilityAccountId', kind: 'ref', ref: 'accounts', required: true },
      { key: 'network', kind: 'text' },
      { key: 'lastFour', kind: 'text' },
      { key: 'isActive', kind: 'boolean' },
    ],
  },
  {
    key: 'number-sequences',
    table: 'number_sequences',
    actorCols: true,
    groupKey: 'billing',
    iconKey: 'hash',
    orgScoped: true,
    orderBy: 'document_kind',
    hasActive: false,
    columns: [
      { key: 'documentKind', kind: 'ref', ref: 'number-sequence-kinds' },
      { key: 'prefix', kind: 'code' },
      { key: 'nextNumber', kind: 'number' },
      { key: 'allocatedThrough', kind: 'number' },
      { key: 'padding', kind: 'number' },
      { key: 'gapless', kind: 'boolean' },
    ],
    fields: [
      { key: 'documentKind', kind: 'ref', ref: 'number-sequence-kinds', required: true, lockedOnEdit: true },
      { key: 'subsidiaryId', kind: 'ref', ref: 'subsidiaries', lockedOnEdit: true },
      { key: 'prefix', kind: 'text', keepDefault: true },
      { key: 'nextNumber', kind: 'integer', required: true, defaultValue: 1 },
      { key: 'padding', kind: 'integer', required: true, defaultValue: 5 },
      { key: 'gapless', kind: 'boolean', helpTextKey: 'fieldHelp.gapless' },
    ],
  },
  {
    key: 'price-levels',
    table: 'price_levels',
    actorCols: true,
    groupKey: 'billing',
    iconKey: 'tag',
    orgScoped: true,
    naturalKey: 'code',
    hasActive: true,
    orderBy: 'is_base desc, name',
    columns: [
      { key: 'code', kind: 'code' },
      { key: 'name', kind: 'text' },
      { key: 'pricingMethod', kind: 'text' },
      { key: 'percentage', kind: 'percent' },
      { key: 'costBasis', kind: 'text' },
      { key: 'isBase', kind: 'boolean' },
      { key: 'isActive', kind: 'badge-active' },
    ],
    fields: [
      { key: 'code', kind: 'text', required: true, lockedOnEdit: true },
      { key: 'name', kind: 'text', required: true },
      { key: 'pricingMethod', kind: 'select', required: true, defaultValue: 'explicit', options: [
        { value: 'explicit', labelKey: 'options.priceLevelMethod.explicit' },
        { value: 'markup_discount', labelKey: 'options.priceLevelMethod.markupDiscount' },
        { value: 'cost_plus', labelKey: 'options.priceLevelMethod.costPlus' },
      ] },
      { key: 'percentage', kind: 'percent' },
      { key: 'costBasis', kind: 'select', options: [
        { value: 'item_cost', labelKey: 'options.priceCostBasis.itemCost' },
        { value: 'standard_cost', labelKey: 'options.priceCostBasis.standardCost' },
        { value: 'average_cost', labelKey: 'options.priceCostBasis.averageCost' },
      ] },
      { key: 'isActive', kind: 'boolean', defaultValue: true },
    ],
  },
  {
    key: 'customer-price-level-assignments',
    table: 'customer_price_level_assignments',
    actorCols: true,
    groupKey: 'billing',
    iconKey: 'tag',
    orgScoped: true,
    hasActive: true,
    orderBy: 'effective_from desc',
    columns: [
      { key: 'customerId', kind: 'ref', ref: 'customers' },
      { key: 'priceLevelId', kind: 'ref', ref: 'price-levels' },
      { key: 'effectiveFrom', kind: 'date' },
      { key: 'effectiveTo', kind: 'date' },
      { key: 'isActive', kind: 'badge-active' },
    ],
    fields: [
      { key: 'customerId', kind: 'ref', ref: 'customers', required: true },
      { key: 'priceLevelId', kind: 'ref', ref: 'price-levels', required: true },
      { key: 'effectiveFrom', kind: 'date', required: true },
      { key: 'effectiveTo', kind: 'date' },
      { key: 'isActive', kind: 'boolean', defaultValue: true },
    ],
  },
  {
    key: 'item-rate-books',
    table: 'item_rate_books',
    rehomed: true, // lives as a tab on the Items catalog module
    rehomedTo: '/items',
    actorCols: true,
    groupKey: 'billing',
    featureKey: 'projects',
    iconKey: 'tag',
    orgScoped: true,
    naturalKey: 'code',
    hasActive: true,
    docSlug: 'item-rates',
    columns: [
      { key: 'code', kind: 'code' },
      { key: 'name', kind: 'text' },
      { key: 'currency', kind: 'code' },
      { key: 'isDefault', kind: 'boolean' },
      { key: 'isActive', kind: 'badge-active' },
    ],
    fields: [
      { key: 'code', kind: 'text', required: true, lockedOnEdit: true },
      { key: 'name', kind: 'text', required: true },
      { key: 'currency', kind: 'ref', ref: 'currencies', required: true },
      { key: 'isDefault', kind: 'boolean' },
      { key: 'isActive', kind: 'boolean', defaultValue: true },
    ],
  },
  {
    key: 'item-rate-book-assignments',
    table: 'item_rate_book_assignments',
    rehomed: true, // lives on the customer & project records as an override section
    rehomedTo: '/parties',
    actorCols: true,
    groupKey: 'billing',
    featureKey: 'projects',
    iconKey: 'tag',
    orgScoped: true,
    orderBy: 'project_id nulls last, customer_id nulls last, effective_from desc nulls last',
    hasActive: true,
    docSlug: 'item-rates',
    columns: [
      { key: 'rateBookId', kind: 'ref', ref: 'item-rate-books' },
      { key: 'customerId', kind: 'ref', ref: 'customers' },
      { key: 'projectId', kind: 'ref', ref: 'projects' },
      { key: 'effectiveFrom', kind: 'date' },
      { key: 'effectiveTo', kind: 'date' },
      { key: 'dateBasis', kind: 'text' },
      { key: 'isActive', kind: 'badge-active' },
    ],
    fields: [
      { key: 'rateBookId', kind: 'ref', ref: 'item-rate-books', required: true },
      { key: 'customerId', kind: 'ref', ref: 'customers' },
      { key: 'projectId', kind: 'ref', ref: 'projects' },
      { key: 'effectiveFrom', kind: 'date' },
      { key: 'effectiveTo', kind: 'date' },
      { key: 'dateBasis', kind: 'select', required: true, defaultValue: 'usage_date', options: [
        { value: 'usage_date', labelKey: 'options.rateDateBasis.usageDate' },
        { value: 'project_start', labelKey: 'options.rateDateBasis.projectStart' },
      ] },
      { key: 'isActive', kind: 'boolean', defaultValue: true },
    ],
  },
]
