import type { SetupEntity, SetupField } from '../types';
const label=(key:string)=>`inspectionPlans.${key}`;
const field=(key:string,kind:SetupField['kind'],extra:Partial<SetupField>={}):SetupField=>({key,kind,labelKey:label(key),...extra});
export const INSPECTION_PLANS_ENTITY:SetupEntity={
  key:'inspection-plans',table:'inventory_inspection_plans',orgScoped:true,actorCols:true,groupKey:'inventory',rehomed:true,featureKey:'manufacturing',iconKey:'clipboard',orderBy:'item_id,point,operation_sequence,effective_from desc',hasActive:false,allowDelete:false,importVia:'none',drawerSize:'xl',mutationPath:'/api/manufacturing/inspection-plans',
  mutationCreateKeys:['name','itemId','point','operationSequence','effectiveFrom','effectiveTo','measures','reason'],mutationUpdateKeys:['name','itemId','point','operationSequence','effectiveFrom','effectiveTo','measures','reason','expectedRevision'],mutationRevision:{requestKey:'expectedRevision',rowColumn:'revision'},
  columns:[{key:'name',kind:'text',labelKey:label('name')},{key:'itemId',kind:'ref',ref:'items',labelKey:label('itemId')},{key:'point',kind:'text',labelKey:label('point')},{key:'operationSequence',kind:'number',labelKey:label('operationSequence')},{key:'effectiveFrom',kind:'date',labelKey:label('effectiveFrom')},{key:'effectiveTo',kind:'date',labelKey:label('effectiveTo')}],
  formSections:[{titleKey:label('basics'),fields:['name','itemId','point','operationSequence','effectiveFrom','effectiveTo']},{titleKey:label('measurements'),descriptionKey:label('help'),fields:['measures']},{titleKey:label('audit'),fields:['reason']}],
  fields:[field('name','text',{required:true}),field('itemId','ref',{ref:'items',required:true}),field('point','select',{required:true,defaultValue:'receipt',options:[{value:'receipt',labelKey:label('receipt')},{value:'operation',labelKey:label('operation')}]}),field('operationSequence','integer',{showWhen:{field:'point',in:['operation']},clearWhenHidden:true}),field('effectiveFrom','date',{required:true}),field('effectiveTo','date'),field('measures','objectArray',{fullWidth:true,defaultValue:[],fields:[field('key','text',{required:true}),field('label','text',{required:true}),field('unit','text',{required:true}),field('required','boolean',{defaultValue:true}),field('minimum','decimal'),field('maximum','decimal')]}),field('reason','textarea',{required:true,resetOnEdit:true,fullWidth:true})],
};
