/** Setup-registry taxes entities (split from registry.ts; pure moves only). */
import type { SetupEntity } from '../types'
import { APPLIES_TO, TAX_CALCULATION_TYPES, TAX_BASIS, SUBMISSION_CHANNELS, GOVERNMENT_FORMATS, TAX_SIGN, JURISDICTION_LEVELS, TAX_TYPES, FILING_FREQUENCIES } from '../options'

export const TAX_ENTITIES: SetupEntity[] = [
  // --- Taxes ---------------------------------------------------------------
  {
    key: 'tax-jurisdictions',
    table: 'tax_jurisdictions',
    singularTitleKey: 'entities.tax-jurisdictions.singularTitle',
    actorCols: true,
    groupKey: 'taxes',
    iconKey: 'map-pin',
    orgScoped: true,
    naturalKey: 'code',
    hasActive: true,
    docSlug: 'tax-jurisdictions-and-nexus',
    columns: [
      { key: 'code', kind: 'code' },
      { key: 'name', kind: 'text' },
      { key: 'country', kind: 'text' },
      { key: 'level', kind: 'text' },
      { key: 'taxType', kind: 'text' },
      { key: 'isActive', kind: 'badge-active' },
    ],
    fields: [
      { key: 'code', kind: 'text', required: true, lockedOnEdit: true },
      { key: 'name', kind: 'text', required: true },
      { key: 'country', kind: 'country', required: true },
      { key: 'region', kind: 'text' },
      { key: 'level', kind: 'select', options: JURISDICTION_LEVELS, keepDefault: true },
      { key: 'taxType', kind: 'select', options: TAX_TYPES, keepDefault: true },
      { key: 'parentId', kind: 'ref', ref: 'tax-jurisdictions' },
      { key: 'isActive', kind: 'boolean' },
    ],
  },
  {
    key: 'tax-registrations',
    table: 'tax_registrations',
    singularTitleKey: 'entities.tax-registrations.singularTitle',
    actorCols: true,
    groupKey: 'taxes',
    iconKey: 'badge-check',
    orgScoped: true,
    hasActive: true,
    docSlug: 'tax-jurisdictions-and-nexus',
    columns: [
      { key: 'jurisdictionId', kind: 'ref', ref: 'tax-jurisdictions' },
      { key: 'registrationNumber', kind: 'text' },
      { key: 'filingFrequency', kind: 'text' },
      { key: 'effectiveFrom', kind: 'date' },
      { key: 'isActive', kind: 'badge-active' },
    ],
    fields: [
      { key: 'jurisdictionId', kind: 'ref', ref: 'tax-jurisdictions', required: true },
      { key: 'registrationNumber', kind: 'text' },
      { key: 'filingFrequency', kind: 'select', options: FILING_FREQUENCIES, keepDefault: true },
      // The org's own configured return forms (by code) — the picker offers
      // only valid, installed forms instead of free text, while the
      // write-time integrity check refuses a form from another jurisdiction.
      { key: 'returnFormCode', kind: 'ref', ref: 'tax-return-forms' },
      { key: 'effectiveFrom', kind: 'date' },
      { key: 'effectiveTo', kind: 'date' },
      { key: 'isActive', kind: 'boolean' },
    ],
  },
  {
    key: 'tax-codes',
    table: 'tax_codes',
    singularTitleKey: 'entities.tax-codes.singularTitle',
    actorCols: true,
    groupKey: 'taxes',
    iconKey: 'receipt',
    orgScoped: true,
    naturalKey: 'code',
    hasActive: true,
    docSlug: 'tax-configuration',
    columns: [
      { key: 'code', kind: 'code' },
      { key: 'name', kind: 'text' },
      { key: 'appliesTo', kind: 'text' },
      { key: 'calculationType', kind: 'text' },
      { key: 'recoverablePercent', kind: 'percent' },
      { key: 'priceIncludesTax', kind: 'boolean' },
      { key: 'isActive', kind: 'badge-active' },
    ],
    fields: [
      { key: 'code', kind: 'text', required: true, lockedOnEdit: true },
      { key: 'name', kind: 'text', required: true },
      { key: 'jurisdictionId', kind: 'ref', ref: 'tax-jurisdictions' },
      { key: 'country', kind: 'country' },
      { key: 'region', kind: 'text' },
      { key: 'appliesTo', kind: 'select', options: APPLIES_TO, keepDefault: true },
      { key: 'calculationType', kind: 'select', options: TAX_CALCULATION_TYPES, keepDefault: true },
      { key: 'collectedAccountId', kind: 'ref', ref: 'accounts' },
      { key: 'paidAccountId', kind: 'ref', ref: 'accounts' },
      { key: 'withholdingAccountId', kind: 'ref', ref: 'accounts' },
      { key: 'recoverablePercent', kind: 'percent', keepDefault: true },
      { key: 'priceIncludesTax', kind: 'boolean' },
      { key: 'compoundOnPrevious', kind: 'boolean' },
      { key: 'roundingScale', kind: 'integer', keepDefault: true },
      { key: 'isActive', kind: 'boolean' },
    ],
  },
  {
    key: 'income-tax-rates',
    table: 'income_tax_rates',
    singularTitleKey: 'entities.income-tax-rates.singularTitle',
    actorCols: true,
    groupKey: 'taxes',
    iconKey: 'percent',
    orgScoped: true,
    hasActive: true,
    docSlug: 'tax-configuration',
    columns: [
      { key: 'jurisdiction', kind: 'text' },
      { key: 'subsidiaryId', kind: 'ref', ref: 'subsidiaries' },
      { key: 'ratePercent', kind: 'percent' },
      { key: 'effectiveFrom', kind: 'date' },
      { key: 'effectiveTo', kind: 'date' },
      { key: 'isActive', kind: 'badge-active' },
    ],
    fields: [
      { key: 'jurisdiction', kind: 'text', required: true },
      { key: 'subsidiaryId', kind: 'ref', ref: 'subsidiaries' },
      { key: 'ratePercent', kind: 'percent', required: true },
      { key: 'effectiveFrom', kind: 'date', required: true },
      { key: 'effectiveTo', kind: 'date' },
      { key: 'isActive', kind: 'boolean' },
    ],
  },
  {
    key: 'tax-rates',
    table: 'tax_rates',
    singularTitleKey: 'entities.tax-rates.singularTitle',
    actorCols: true,
    groupKey: 'taxes',
    iconKey: 'percent',
    orgScoped: true,
    orderBy: 'effective_from desc',
    hasActive: false,
    docSlug: 'tax-configuration',
    nestedUnder: 'tax-codes',
    columns: [
      { key: 'taxCodeId', kind: 'ref', ref: 'tax-codes' },
      { key: 'ratePercent', kind: 'percent' },
      { key: 'effectiveFrom', kind: 'date' },
      { key: 'effectiveTo', kind: 'date' },
    ],
    fields: [
      { key: 'taxCodeId', kind: 'ref', ref: 'tax-codes', required: true },
      { key: 'ratePercent', kind: 'percent', required: true },
      { key: 'effectiveFrom', kind: 'date', required: true },
      { key: 'effectiveTo', kind: 'date' },
    ],
  },
  {
    key: 'tax-groups',
    table: 'tax_groups',
    groupKey: 'taxes',
    iconKey: 'layers',
    orgScoped: true,
    naturalKey: 'code',
    hasActive: true,
    docSlug: 'tax-configuration',
    columns: [
      { key: 'code', kind: 'code' },
      { key: 'name', kind: 'text' },
      { key: 'priceIncludesTax', kind: 'boolean' },
      { key: 'isActive', kind: 'badge-active' },
    ],
    fields: [
      { key: 'code', kind: 'text', required: true, lockedOnEdit: true },
      { key: 'name', kind: 'text', required: true },
      { key: 'priceIncludesTax', kind: 'boolean' },
      { key: 'members', kind: 'multiref', ref: 'tax-codes' },
      { key: 'isActive', kind: 'boolean' },
    ],
  },
  {
    // A configurable government return: openbooks computes the boxes from the
    // ledger, renders a facsimile, and routes filing to the jurisdiction's real
    // channel. New jurisdictions are data (a form + its boxes), not code.
    key: 'tax-return-forms',
    table: 'tax_return_forms',
    // Referencing rows (registrations) store the form CODE, not the row id —
    // pickers offer the code and the coercer accepts it as a natural key.
    refValue: 'code',
    actorCols: true,
    groupKey: 'taxes',
    iconKey: 'file',
    orgScoped: true,
    naturalKey: 'code',
    hasActive: true,
    docSlug: 'tax-returns-and-boxes',
    columns: [
      { key: 'code', kind: 'code' },
      { key: 'name', kind: 'text' },
      { key: 'country', kind: 'text' },
      { key: 'submissionChannel', kind: 'text', options: SUBMISSION_CHANNELS },
      { key: 'officialPdfFileId', kind: 'boolean' },
      { key: 'isActive', kind: 'badge-active' },
    ],
    fields: [
      { key: 'code', kind: 'text', required: true, lockedOnEdit: true },
      { key: 'name', kind: 'text', required: true },
      { key: 'country', kind: 'country' },
      { key: 'region', kind: 'text' },
      { key: 'submissionChannel', kind: 'select', options: SUBMISSION_CHANNELS, keepDefault: true },
      { key: 'governmentFormat', kind: 'select', options: GOVERNMENT_FORMATS, keepDefault: true, hidden: true },
      { key: 'submissionUrl', kind: 'text' },
      { key: 'watermark', kind: 'text' },
      { key: 'isActive', kind: 'boolean' },
    ],
  },
  {
    key: 'tax-report-lines',
    table: 'tax_report_lines',
    singularTitleKey: 'entities.tax-report-lines.singularTitle',
    actorCols: true,
    groupKey: 'taxes',
    iconKey: 'file',
    orgScoped: true,
    orderBy: 'report_code, sequence, line_code',
    hasActive: false,
    docSlug: 'tax-returns-and-boxes',
    nestedUnder: 'tax-return-forms',
    columns: [
      { key: 'reportCode', kind: 'code' },
      { key: 'sequence', kind: 'number' },
      { key: 'lineCode', kind: 'code' },
      { key: 'label', kind: 'text' },
      { key: 'basis', kind: 'text' },
    ],
    fields: [
      { key: 'reportCode', kind: 'text', required: true },
      { key: 'lineCode', kind: 'text', required: true },
      { key: 'label', kind: 'text', required: true },
      { key: 'sequence', kind: 'integer', keepDefault: true },
      { key: 'taxCodeId', kind: 'ref', ref: 'tax-codes' },
      { key: 'basis', kind: 'select', options: TAX_BASIS },
      { key: 'sign', kind: 'select', options: TAX_SIGN },
      { key: 'formula', kind: 'text' },
      { key: 'pdfField', kind: 'text' },
    ],
  },
]
