import type { SetupEntity, SetupField } from './types'

const label = (key: string) => `training.${key}`
const reason: SetupField = {
  key: 'reason',
  kind: 'textarea',
  required: true,
  resetOnEdit: true,
  labelKey: label('reason'),
  helpTextKey: label('reasonHint'),
}
const employer: SetupField = {
  key: 'subsidiaryId',
  kind: 'ref',
  ref: 'subsidiaries',
  legalEmployer: true,
  required: true,
  labelKey: 'fields.legalEmployer',
}
const common = {
  groupKey: 'workforce',
  featureKey: 'hrmTraining',
  orgScoped: true,
  actorCols: true,
  hasActive: false,
  rehomed: true,
  iconKey: 'graduation-cap',
  importVia: 'none',
  allowUpdate: false,
  allowDelete: false,
  writePermission: 'hrm.certifications.manage',
} as const
const statuses = (values: string[]) => values.map((value) => ({ value, labelKey: label(`statuses.${value}`) }))

/** CompensationPackagesSection is the exemplar: approved policy owns delivery and participant records. */
export const TRAINING_COURSES_ENTITY: SetupEntity = {
  ...common,
  key: 'training-courses',
  table: 'hrm_training_courses',
  orderBy: 'code,version desc,id',
  mutationPath: '/api/hrm/training/courses',
  createDestination: { rowParam: 'course', tabKey: 'review' },
  mutationCreateKeys: [
    'subsidiaryId',
    'code',
    'version',
    'name',
    'description',
    'effectiveFrom',
    'effectiveTo',
    'qualificationTypeId',
    'minimumAttendancePercent',
    'passingScore',
    'reason',
  ],
  columns: [
    { key: 'code', kind: 'code' },
    { key: 'version', kind: 'number', labelKey: label('version') },
    { key: 'name', kind: 'text' },
    { key: 'subsidiaryId', kind: 'ref', ref: 'subsidiaries', labelKey: 'fields.legalEmployer' },
    { key: 'effectiveFrom', kind: 'date' },
    { key: 'effectiveTo', kind: 'date' },
    {
      key: 'status',
      kind: 'badge',
      options: statuses(['draft', 'approved', 'retired', 'cancelled']),
      labelKey: label('status'),
    },
  ],
  fields: [
    employer,
    { key: 'code', kind: 'text', required: true },
    { key: 'version', kind: 'integer', min: 1, required: true, labelKey: label('version') },
    { key: 'name', kind: 'text', required: true },
    { key: 'description', kind: 'textarea' },
    { key: 'effectiveFrom', kind: 'date', required: true },
    { key: 'effectiveTo', kind: 'date' },
    {
      key: 'qualificationTypeId',
      kind: 'ref',
      ref: 'qualification-types',
      labelKey: label('qualificationType'),
      helpTextKey: label('qualificationHint'),
    },
    {
      key: 'minimumAttendancePercent',
      kind: 'integer',
      min: 0,
      max: 100,
      required: true,
      labelKey: label('attendanceThreshold'),
    },
    {
      key: 'passingScore',
      kind: 'integer',
      min: 0,
      max: 100,
      labelKey: label('passingScore'),
      helpTextKey: label('scoreHint'),
    },
    reason,
  ],
  creationSteps: [
    {
      key: 'identity',
      titleKey: label('courseIdentity'),
      descriptionKey: label('courseIdentityHint'),
      fields: ['subsidiaryId', 'code', 'version', 'name', 'description', 'effectiveFrom', 'effectiveTo'],
    },
    {
      key: 'policy',
      titleKey: label('completionPolicy'),
      descriptionKey: label('completionPolicyHint'),
      fields: ['qualificationTypeId', 'minimumAttendancePercent', 'passingScore', 'reason'],
    },
  ],
}
export const TRAINING_SESSIONS_ENTITY: SetupEntity = {
  ...common,
  key: 'training-sessions',
  table: 'hrm_training_sessions',
  orderBy: 'starts_at desc,id',
  nestedUnder: 'training-courses',
  parentRecords: [{ entityKey: 'training-courses', fieldKey: 'courseId' }],
  mutationPath: '/api/hrm/training/courses',
  createDestination: { rowParam: 'childRow', tabKey: 'review' },
  mutationCreateKeys: ['name', 'location', 'startsAt', 'endsAt', 'timeZone', 'capacity', 'reason'],
  columns: [
    { key: 'name', kind: 'text' },
    { key: 'startsOn', kind: 'date', labelKey: label('startsOn') },
    { key: 'endsOn', kind: 'date', labelKey: label('endsOn') },
    { key: 'location', kind: 'text', labelKey: label('location') },
    { key: 'capacity', kind: 'number', labelKey: label('capacity') },
    {
      key: 'status',
      kind: 'badge',
      labelKey: label('status'),
      options: statuses(['draft', 'scheduled', 'in_progress', 'completed', 'cancelled']),
    },
  ],
  fields: [
    { ...employer, hidden: true },
    { key: 'courseId', kind: 'ref', ref: 'training-courses', hidden: true, required: true, labelKey: label('course') },
    { key: 'name', kind: 'text', required: true },
    { key: 'location', kind: 'text', required: true, labelKey: label('location') },
    { key: 'timeZone', kind: 'timeZone', required: true, labelKey: label('timeZone') },
    { key: 'startsAt', kind: 'zonedDateTime', timeZoneField: 'timeZone', required: true, labelKey: label('startsAt') },
    { key: 'endsAt', kind: 'zonedDateTime', timeZoneField: 'timeZone', required: true, labelKey: label('endsAt') },
    { key: 'capacity', kind: 'integer', min: 1, max: 10000, required: true, labelKey: label('capacity') },
    reason,
  ],
}
export const TRAINING_PARTICIPANTS_ENTITY: SetupEntity = {
  ...common,
  key: 'training-participants',
  table: 'hrm_training_participants',
  orderBy: 'created_at,id',
  nestedUnder: 'training-sessions',
  parentRecords: [{ entityKey: 'training-sessions', fieldKey: 'sessionId' }],
  mutationPath: '/api/hrm/training/sessions',
  createDestination: { rowParam: 'childChildRow', tabKey: 'review' },
  mutationCreateKeys: ['employmentId', 'reason'],
  columns: [
    { key: 'employmentId', kind: 'ref', ref: 'worker-employments', labelKey: label('employment') },
    {
      key: 'status',
      kind: 'badge',
      labelKey: label('status'),
      options: statuses(['invited', 'accepted', 'declined', 'completed', 'failed', 'voided', 'cancelled']),
    },
    { key: 'attendanceSeconds', kind: 'number', labelKey: label('attendanceSeconds') },
    { key: 'score', kind: 'number', labelKey: label('score') },
  ],
  fields: [
    { ...employer, hidden: true },
    {
      key: 'sessionId',
      kind: 'ref',
      ref: 'training-sessions',
      hidden: true,
      required: true,
      labelKey: label('session'),
    },
    {
      key: 'employmentId',
      kind: 'ref',
      ref: 'worker-employments',
      refScopeField: 'subsidiaryId',
      required: true,
      labelKey: label('employment'),
    },
    reason,
  ],
}
