'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { useTranslations } from 'next-intl'
import { Badge, Button, Input, Label, SearchSelect, Select, Table, TableBody, TableCell, TableHead, TableHeader, TableRow, Textarea, UrlDrawer } from '@openbooks/ui'
import { Plus, Trash2 } from 'lucide-react'
import { toast } from 'sonner'

export function OpportunityDrawer({ data, statuses, accounts, contacts, owners, teams, sources, items, currencies, canManage }: { data:any; statuses:any[]; accounts:any[]; contacts:any[]; owners:any[]; teams:any[]; sources:any[]; items:any[]; currencies:{code:string;name:string}[]; canManage:boolean }) {
  const t=useTranslations('crm'); const tc=useTranslations('common'); const router=useRouter(); const row=data.opportunity
  const [form,setForm]=useState({ title:row.title==='New opportunity'?'':row.title, partyId:row.party_id??'', primaryContactId:row.primary_contact_id??'', ownerUserId:row.owner_user_id??'', salesTeamId:row.sales_team_id??'', statusId:row.status_id, leadSourceId:row.lead_source_id??'', expectedCloseDate:row.expected_close_date??'', forecastCategory:row.forecast_category, probability:String(row.probability), currency:row.currency, nextStep:row.next_step??'', description:row.description??'', winLossReason:row.win_loss_reason??'' })
  const [lines,setLines]=useState<any[]>(data.lines.map((line:any)=>({itemId:line.item_id??'',description:line.description??'',quantity:String(line.quantity),unit:line.unit??'',unitPrice:String(line.unit_price)})))
  const [busy,setBusy]=useState(false); const set=(key:string,value:unknown)=>setForm(current=>({...current,[key]:value}))
  async function save(){ if(!form.title.trim()) return toast.error(t('validation.titleRequired')); setBusy(true); try { const response=await fetch(`/api/crm/opportunities/${row.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({...form,partyId:form.partyId||null,primaryContactId:form.primaryContactId||null,ownerUserId:form.ownerUserId||null,salesTeamId:form.salesTeamId||null,leadSourceId:form.leadSourceId||null,expectedCloseDate:form.expectedCloseDate||null,probability:Number(form.probability),lines})}); if(!response.ok) throw new Error(); toast.success(tc('feedback.saved')); router.refresh() }catch{toast.error(tc('feedback.saveFailed'))}finally{setBusy(false)} }
  async function estimate(){setBusy(true);try{const response=await fetch(`/api/crm/opportunities/${row.id}/estimate`,{method:'POST'});const result=await response.json();if(!response.ok)throw new Error();toast.success(t('opportunities.estimateCreated'));router.push(`/estimates?estimate=${result.id}`)}catch{toast.error(t('opportunities.estimateFailed'));setBusy(false)}}
  const accountContacts=contacts.filter((c:any)=>!form.partyId||c.party_id===form.partyId)
  return <UrlDrawer open closeHref="/crm/opportunities" size="2xl" title={<span className="flex items-center gap-2">{row.opportunity_number} · {form.title||t('opportunities.newFallback')}<Badge>{row.status_name}</Badge></span>} headerActions={canManage?<><Button variant="outline" onClick={estimate} disabled={busy||!form.partyId||!lines.length}>{t('opportunities.createEstimate')}</Button><Button onClick={save} disabled={busy}>{busy?tc('actions.saving'):tc('actions.save')}</Button></>:undefined}>
    <div className="grid gap-4 sm:grid-cols-3">
      <div className="sm:col-span-2"><Field label={t('fields.title')}><Input value={form.title} onChange={e=>set('title',e.target.value)} disabled={!canManage}/></Field></div>
      <Field label={t('fields.account')}><Select value={form.partyId} onChange={e=>{set('partyId',e.target.value);set('primaryContactId','')}} disabled={!canManage}><option value="">{tc('labels.none')}</option>{accounts.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</Select></Field>
      <Field label={t('fields.primaryContact')}><Select value={form.primaryContactId} onChange={e=>set('primaryContactId',e.target.value)} disabled={!canManage}><option value="">{tc('labels.none')}</option>{accountContacts.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</Select></Field>
      <Field label={t('fields.owner')}><Select value={form.ownerUserId} onChange={e=>set('ownerUserId',e.target.value)} disabled={!canManage}><option value="">{t('fields.unassigned')}</option>{owners.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</Select></Field>
      <Field label={t('fields.salesTeam')}><Select value={form.salesTeamId} onChange={e=>set('salesTeamId',e.target.value)} disabled={!canManage}><option value="">{tc('labels.none')}</option>{teams.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</Select></Field>
      <Field label={t('fields.status')}><Select value={form.statusId} onChange={e=>set('statusId',e.target.value)} disabled={!canManage}>{statuses.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</Select></Field>
      <Field label={t('fields.probability')}><Input type="number" min="0" max="100" value={form.probability} onChange={e=>set('probability',e.target.value)} disabled={!canManage}/></Field>
      <Field label={t('fields.forecastCategory')}><Select value={form.forecastCategory} onChange={e=>set('forecastCategory',e.target.value)} disabled={!canManage}>{['omitted','worst_case','most_likely','upside'].map(v=><option key={v} value={v}>{t(`forecastCategories.${v}`)}</option>)}</Select></Field>
      <Field label={t('fields.expectedClose')}><Input type="date" value={form.expectedCloseDate} onChange={e=>set('expectedCloseDate',e.target.value)} disabled={!canManage}/></Field>
      <Field label={t('fields.currency')}><SearchSelect value={form.currency} onChange={value=>set('currency',value)} options={currencies.map(currency=>({value:currency.code,label:`${currency.code} · ${currency.name}`}))} ariaLabel={t('fields.currency')} disabled={!canManage}/></Field>
      <Field label={t('fields.leadSource')}><Select value={form.leadSourceId} onChange={e=>set('leadSourceId',e.target.value)} disabled={!canManage}><option value="">{tc('labels.none')}</option>{sources.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</Select></Field>
      <div className="sm:col-span-3"><Field label={t('fields.nextStep')}><Input value={form.nextStep} onChange={e=>set('nextStep',e.target.value)} disabled={!canManage}/></Field></div>
    </div>
    <section className="mt-7"><div className="mb-2 flex items-center justify-between"><h3 className="font-semibold">{t('opportunities.lines')}</h3>{canManage?<Button variant="outline" size="sm" onClick={()=>setLines(current=>[...current,{itemId:'',description:'',quantity:'1',unit:'',unitPrice:'0'}])}><Plus size={14}/>{t('opportunities.addLine')}</Button>:null}</div><div className="overflow-x-auto rounded-md border dark:border-slate-800"><Table><TableHeader><TableRow><TableHead>{t('fields.item')}</TableHead><TableHead>{t('fields.description')}</TableHead><TableHead>{t('fields.quantity')}</TableHead><TableHead>{t('fields.unitPrice')}</TableHead><TableHead/></TableRow></TableHeader><TableBody>{lines.map((line,index)=><TableRow key={index}><TableCell><Select value={line.itemId} onChange={e=>setLines(current=>current.map((v,i)=>i===index?{...v,itemId:e.target.value}:v))} disabled={!canManage}><option value="">{t('opportunities.selectItem')}</option>{items.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</Select></TableCell><TableCell><Input value={line.description} onChange={e=>setLines(current=>current.map((v,i)=>i===index?{...v,description:e.target.value}:v))}/></TableCell><TableCell><Input className="w-24 text-right tabular-nums" value={line.quantity} onChange={e=>setLines(current=>current.map((v,i)=>i===index?{...v,quantity:e.target.value}:v))}/></TableCell><TableCell><Input className="w-32 text-right tabular-nums" value={line.unitPrice} onChange={e=>setLines(current=>current.map((v,i)=>i===index?{...v,unitPrice:e.target.value}:v))}/></TableCell><TableCell>{canManage?<Button variant="ghost" size="icon" aria-label={tc('actions.delete')} onClick={()=>setLines(current=>current.filter((_,i)=>i!==index))}><Trash2 size={15}/></Button>:null}</TableCell></TableRow>)}</TableBody></Table></div></section>
    <div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label={t('fields.description')}><Textarea rows={5} value={form.description} onChange={e=>set('description',e.target.value)} disabled={!canManage}/></Field><Field label={t('fields.winLossReason')}><Textarea rows={5} value={form.winLossReason} onChange={e=>set('winLossReason',e.target.value)} disabled={!canManage}/></Field></div>
  </UrlDrawer>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>}
