import type { BoardWindow, BoardEntry } from '../components/scheduling/model'
/** Native-shaped scheduling snapshots for component lifecycle and presentation controls. */
export function scheduleWindow(
  from = '2026-10-12',
  through = from,
): BoardWindow {
  const board = {
    id: 'aa010000-0000-4000-8000-000000000001',
    code: 'CREW',
    name: 'Crew',
    rowKind: 'people',
    resourceKind: null,
    views: ['grid', 'targets', 'calendar', 'timeline'],
    defaultView: 'grid',
    showWeekends: true,
    showTotals: false,
    showHoursColumn: true,
    distributionVisibility: 'personal',
    weekendDays: ['6', '7'],
    cellColorRules: [],
    timeZone: 'America/Toronto',
    rangeDays: 7,
    weekStartsOn: 0,
    grain: 'day',
    dayPolicyKnown: true,
    dayStarts: '07:00',
    dayEnds: '15:30',
    dayBreakMinutes: 30,
    publishPolicy: 'live',
    isActive: true,
    projectId: null,
  }
  const subjects = [
    'aa010000-0000-4000-8000-000000000002',
    'aa010000-0000-4000-8000-000000000003',
  ]
  const entry = (index: number): BoardEntry => ({
    id: `aa010000-0000-4000-8000-00000000000${index + 4}`,
    boardId: board.id,
    boardName: board.name,
    revision: 1,
    subjectId: subjects[index]!,
    subjectKind: 'person',
    workerPartyId: subjects[index]!,
    status: 'published',
    startsOn: from,
    endsOn: from,
    startsAt: `${from}T11:00:00Z`,
    endsAt: `${from}T19:30:00Z`,
    startClock: '07:00',
    endClock: '15:30',
    workedMinutes: 480,
    breakMinutes: 30,
    spanMode: 'day',
    target: {
      kind: 'code',
      id: 'aa010000-0000-4000-8000-000000000006',
      code: 'SHOP',
      label: 'Shop',
      color: index ? '#00ff00' : '#ff0000',
      context: null,
      counts: true,
    },
    detail: null,
    notes: null,
    departmentId: null,
    departmentName: null,
    projectTaskId: null,
    projectTaskName: null,
    seriesId: null,
    supersedesId: null,
    updatedAt: `${from}T10:00:00Z`,
    updatedByName: 'Scheduler',
  })
  return {
    board,
    from,
    through,
    days: [
      { date: from, isWeekend: false, isHoliday: false, holidayName: null },
    ],
    rows: subjects.map((subjectId, i) => ({
      subjectId,
      subjectKind: 'person',
      name: i ? 'Blair' : 'Alex',
      shortCode: null,
      jobTitle: null,
      departmentId: null,
      departmentName: null,
      tradeName: null,
      inScope: true,
    })),
    entries: [entry(0), entry(1)],
    sourceRecords: [],
    replaced: [],
    absences: [],
    codes: [],
    canManage: false,
    canPublish: false,
  } as unknown as BoardWindow
}
